<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011
 */ 
class EstadocajaDAO { 

	public static function insertarEstadocaja(Estadocaja $oEstadocaja) { 
		$db = DbManager::getConnection(); 

		
		$cd_estadocaja = $oEstadocaja->getCd_estadocaja();
		
		$ds_estadocaja = $oEstadocaja->getDs_estadocaja();
		

		$sql = "INSERT INTO estadocaja (ds_estadocaja) VALUES('$ds_estadocaja')"; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function modificarEstadocaja(Estadocaja $oEstadocaja) { 
		$db = DbManager::getConnection(); 

		
		$cd_estadocaja = $oEstadocaja->getCd_estadocaja();
		
		$ds_estadocaja = $oEstadocaja->getDs_estadocaja();
		


		$sql = "UPDATE estadocaja SET ds_estadocaja = '$ds_estadocaja' WHERE cd_estadocaja = $cd_estadocaja "; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function eliminarEstadocaja(Estadocaja $oEstadocaja) { 
		$db = DbManager::getConnection(); 

		$cd_estadocaja = $oEstadocaja->getCd_estadocaja();

		$sql = "DELETE FROM estadocaja WHERE cd_estadocaja = $cd_estadocaja "; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function getEstadoscajas(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT * FROM estadocaja "; 
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$items = ResultFactory::toCollection($db, $result, new EstadocajaFactory());
		$db->sql_freeresult($result);
		return $items;
	}


	public static function getCantEstadoscajas(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT count(*) as count FROM estadocaja "; 
		$sql .= $criterio->buildFiltroSinPaginar();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$next = $db->sql_fetchassoc($result);
		$cant = $next['count'];
		$db->sql_freeresult($result);
		return ((int) $cant);
	}


	public static function getEstadocaja(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT * FROM estadocaja "; 
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		if ($db->sql_numrows() > 0) {
			$temp = $db->sql_fetchassoc($result);
			$factory = new EstadocajaFactory();
			$obj = $factory->build($temp);
		}
		$db->sql_freeresult($result);
		return $obj;
	}

} 
?>
