<?php

/**
 * Autogenerated class
 *
 *  @author modelBuilder
 *  @since 18-05-2021
 */
class MedioDAO {

	public static function insertarMedio(Medio $oMedio) {
		$db = DbManager::getConnection();


		$cd_medio = $oMedio->getCd_medio();

		$ds_medio = $oMedio->getDs_medio();


		$sql = "INSERT INTO medio (ds_medio) VALUES('$ds_medio')";

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function modificarMedio(Medio $oMedio) {
		$db = DbManager::getConnection();


		$cd_medio = $oMedio->getCd_medio();

		$ds_medio = $oMedio->getDs_medio();



		$sql = "UPDATE medio SET ds_medio = '$ds_medio' WHERE cd_medio = $cd_medio ";

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function eliminarMedio(Medio $oMedio) {
		$db = DbManager::getConnection();

		$cd_medio = $oMedio->getCd_medio();

		$sql = "DELETE FROM medio WHERE cd_medio = $cd_medio ";

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function getMedios(CriterioBusqueda $criterio) {
		$db = DbManager::getConnection();


		$sql = "SELECT * FROM medio ";
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$items = ResultFactory::toCollection($db, $result, new MedioFactory());
		$db->sql_freeresult($result);
		return $items;
	}


	public static function getCantMedios(CriterioBusqueda $criterio) {
		$db = DbManager::getConnection();


		$sql = "SELECT count(*) as count FROM medio ";
		$sql .= $criterio->buildFiltroSinPaginar();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$next = $db->sql_fetchassoc($result);
		$cant = $next['count'];
		$db->sql_freeresult($result);
		return ((int) $cant);
	}


	public static function getMedio(CriterioBusqueda $criterio) {
		$db = DbManager::getConnection();


		$sql = "SELECT * FROM medio ";
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		if ($db->sql_numrows() > 0) {
			$temp = $db->sql_fetchassoc($result);
			$factory = new MedioFactory();
			$obj = $factory->build($temp);
		}
		$db->sql_freeresult($result);
		return $obj;
	}

}
?>
