<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011
 */
class MovcajacontrolpracticaDAO {

   

    public static function getMovcajacontrolpracticas($cd_obrasocial, $cd_practica1, $cd_practica2) {
        $db = DbManager::getConnection();
        $sql = "SELECT MCCP.*, P1.ds_practica, P2.ds_practica AS ds_practica2, OS.ds_obrasocial  FROM movcajacontrolpractica MCCP";
        $sql .= " LEFT JOIN practica P1 ON ( MCCP.cd_practica1 = P1.cd_practica )";
        $sql .= " LEFT JOIN practica P2 ON ( MCCP.cd_practica2 = P2.cd_practica )";
		$sql .= " LEFT JOIN obrasocial OS ON ( MCCP.cd_obrasocial = OS.cd_obrasocial )";
        //$sql .= $criterio->buildFiltro();
        $sql .= " WHERE   OS.cd_obrasocial = $cd_obrasocial AND  ((P1.cd_practica = $cd_practica1 AND  P2.cd_practica = $cd_practica2) OR (P2.cd_practica = $cd_practica1 AND  P1.cd_practica = $cd_practica2))";
        //echo "<br/>" . $sql;
        $result = $db->sql_query($sql);
        if (!$result)//hubo un error en la bbdd.
            throw new DBException($db->sql_error());

        $items = ResultFactory::toCollection($db, $result, new MovcajacontrolpracticaFactory());
        $db->sql_freeresult($result);
        return $items;
    }

    

    public static function getCantMovcajacontrolpracticas(CriterioBusqueda $criterio) {
        $db = DbManager::getConnection();


        $sql = "SELECT count(*) as count FROM movcajacontrolpractica ";
        $sql .= $criterio->buildFiltroSinPaginar();
        $result = $db->sql_query($sql);
        if (!$result)//hubo un error en la bbdd.
            throw new DBException($db->sql_error());

        $next = $db->sql_fetchassoc($result);
        $cant = $next['count'];
        $db->sql_freeresult($result);
        return ((int) $cant);
    }

    public static function getMovcajacontrolpractica(CriterioBusqueda $criterio) {
        $db = DbManager::getConnection();


        $sql = "SELECT * FROM movcajacontrolpractica ";
        $sql .= $criterio->buildFiltro();
        $result = $db->sql_query($sql);
        if (!$result)//hubo un error en la bbdd.
            throw new DBException($db->sql_error());

        if ($db->sql_numrows() > 0) {
            $temp = $db->sql_fetchassoc($result);
            $factory = new MovcajacontrolpracticaFactory();
            $obj = $factory->build($temp);
        }
        $db->sql_freeresult($result);
        return $obj;
    }
    
    

	
}
?>
