<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 24-11-2011
 */ 
class ObrasocialDAO { 

	public static function insertarObrasocial(Obrasocial $oObrasocial) { 
		$db = DbManager::getConnection(); 

		
		$cd_obrasocial = $oObrasocial->getCd_obrasocial();
		
		$ds_obrasocial = $oObrasocial->getDs_obrasocial();
		
		$bl_activa = ($oObrasocial->getBl_activa())?$oObrasocial->getBl_activa():0;
		

		$sql = "INSERT INTO obrasocial (ds_obrasocial, bl_activa) VALUES('$ds_obrasocial', '$bl_activa')"; 
		
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function modificarObrasocial(Obrasocial $oObrasocial) { 
		$db = DbManager::getConnection(); 

		
		$cd_obrasocial = $oObrasocial->getCd_obrasocial();
		
		$ds_obrasocial = $oObrasocial->getDs_obrasocial();
		
		$bl_activa = ($oObrasocial->getBl_activa())?$oObrasocial->getBl_activa():0;

		$sql = "UPDATE obrasocial SET ds_obrasocial = '$ds_obrasocial', bl_activa = '$bl_activa' WHERE cd_obrasocial = $cd_obrasocial "; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function eliminarObrasocial(Obrasocial $oObrasocial) { 
		$db = DbManager::getConnection(); 

		$cd_obrasocial = $oObrasocial->getCd_obrasocial();

		$sql = "DELETE FROM obrasocial WHERE cd_obrasocial = $cd_obrasocial "; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function getObrasociales(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT * FROM obrasocial "; 
		$sql .= $criterio->buildFiltro();
                
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$items = ResultFactory::toCollection($db, $result, new ObrasocialFactory());
		$db->sql_freeresult($result);
		return $items;
	}


	public static function getCantObrasociales(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 
		$sql = "SELECT count(*) as count FROM obrasocial "; 
		$sql .= $criterio->buildFiltroSinPaginar();
                
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$next = $db->sql_fetchassoc($result);
		$cant = $next['count'];
		$db->sql_freeresult($result);
		return ((int) $cant);
	}


	public static function getObrasocial(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT * FROM obrasocial "; 
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		if ($db->sql_numrows() > 0) {
			$temp = $db->sql_fetchassoc($result);
			$factory = new ObrasocialFactory();
			$obj = $factory->build($temp);
		}
		$db->sql_freeresult($result);
		return $obj;
	}

} 
?>
