<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 24-11-2011
 */ 
class PracticaDAO { 

	public static function insertarPractica(Practica $oPractica) { 
		$db = DbManager::getConnection(); 

		
		$cd_practica = $oPractica->getCd_practica();
		
		$ds_practica = $oPractica->getDs_practica();
		
		$bl_activa = $oPractica->getBl_activa();
		

		$sql = "INSERT INTO practica (ds_practica, bl_activa) VALUES('$ds_practica', '$bl_activa')"; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function modificarPractica(Practica $oPractica) { 
		$db = DbManager::getConnection(); 

		
		$cd_practica = $oPractica->getCd_practica();
		
		$ds_practica = $oPractica->getDs_practica();
		
		$bl_activa = $oPractica->getBl_activa();

		$sql = "UPDATE practica SET ds_practica = '$ds_practica', bl_activa = '$bl_activa' WHERE cd_practica = $cd_practica "; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function eliminarPractica(Practica $oPractica) { 
		$db = DbManager::getConnection(); 

		$cd_practica = $oPractica->getCd_practica();

		$sql = "DELETE FROM practica WHERE cd_practica = $cd_practica "; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function getPracticas(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT * FROM practica "; 
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$items = ResultFactory::toCollection($db, $result, new PracticaFactory());
		$db->sql_freeresult($result);
		return $items;
	}


	public static function getCantPracticas(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT count(*) as count FROM practica "; 
		$sql .= $criterio->buildFiltroSinPaginar();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$next = $db->sql_fetchassoc($result);
		$cant = $next['count'];
		$db->sql_freeresult($result);
		return ((int) $cant);
	}


	public static function getPractica(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT * FROM practica "; 
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		if ($db->sql_numrows() > 0) {
			$temp = $db->sql_fetchassoc($result);
			$factory = new PracticaFactory();
			$obj = $factory->build($temp);
		}
		$db->sql_freeresult($result);
		return $obj;
	}

} 
?>
