<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 28-10-2011
 */ 
class TipoPersonalDAO { 

	public static function insertarTipoPersonal(TipoPersonal $oTipoPersonal) { 
		$db = DbManager::getConnection(); 

		
		$cd_tipopersonal = $oTipoPersonal->getCd_tipopersonal();
		
		$ds_tipopersonal = $oTipoPersonal->getDs_tipopersonal();
		

		$sql = "INSERT INTO tipopersonal (ds_tipopersonal) VALUES('$ds_tipopersonal')"; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function modificarTipoPersonal(TipoPersonal $oTipoPersonal) { 
		$db = DbManager::getConnection(); 

		
		$cd_tipopersonal = $oTipoPersonal->getCd_tipopersonal();
		
		$ds_tipopersonal = $oTipoPersonal->getDs_tipopersonal();
		


		$sql = "UPDATE tipopersonal SET ds_tipopersonal = '$ds_tipopersonal' WHERE cd_tipopersonal = $cd_tipopersonal "; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function eliminarTipoPersonal(TipoPersonal $oTipoPersonal) { 
		$db = DbManager::getConnection(); 

		$cd_tipopersonal = $oTipoPersonal->getCd_tipopersonal();

		$sql = "DELETE FROM tipopersonal WHERE cd_tipopersonal = $cd_tipopersonal "; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function getTipoPersonales(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT * FROM tipopersonal "; 
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$items = ResultFactory::toCollection($db, $result, new TipoPersonalFactory());
		$db->sql_freeresult($result);
		return $items;
	}


	public static function getCantTipoPersonales(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT count(*) as count FROM tipopersonal "; 
		$sql .= $criterio->buildFiltroSinPaginar();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$next = $db->sql_fetchassoc($result);
		$cant = $next['count'];
		$db->sql_freeresult($result);
		return ((int) $cant);
	}


	public static function getTipoPersonal(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT * FROM tipopersonal "; 
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		if ($db->sql_numrows() > 0) {
			$temp = $db->sql_fetchassoc($result);
			$factory = new TipoPersonalFactory();
			$obj = $factory->build($temp);
		}
		$db->sql_freeresult($result);
		return $obj;
	}

} 
?>
