<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 28-10-2011
 */ 
class TipoDocumentoDAO { 

	public static function insertarTipoDocumento(TipoDocumento $oTipoDocumento) { 
		$db = DbManager::getConnection(); 

		
		$cd_tipodocumento = $oTipoDocumento->getCd_tipodocumento();
		
		$ds_tipodocumento = $oTipoDocumento->getDs_tipodocumento();
		

		$sql = "INSERT INTO tipodocumento (ds_tipodocumento) VALUES('$ds_tipodocumento')"; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function modificarTipoDocumento(TipoDocumento $oTipoDocumento) { 
		$db = DbManager::getConnection(); 

		
		$cd_tipodocumento = $oTipoDocumento->getCd_tipodocumento();
		
		$ds_tipodocumento = $oTipoDocumento->getDs_tipodocumento();
		


		$sql = "UPDATE tipodocumento SET ds_tipodocumento = '$ds_tipodocumento' WHERE cd_tipodocumento = $cd_tipodocumento "; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function eliminarTipoDocumento(TipoDocumento $oTipoDocumento) { 
		$db = DbManager::getConnection(); 

		$cd_tipodocumento = $oTipoDocumento->getCd_tipodocumento();

		$sql = "DELETE FROM tipodocumento WHERE cd_tipodocumento = $cd_tipodocumento "; 

		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$db->sql_freeresult($result);
	}


	public static function getTipoDocumentos(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT * FROM tipodocumento "; 
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$items = ResultFactory::toCollection($db, $result, new TipoDocumentoFactory());
		$db->sql_freeresult($result);
		return $items;
	}


	public static function getCantTipoDocumentos(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT count(*) as count FROM tipodocumento "; 
		$sql .= $criterio->buildFiltroSinPaginar();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		$next = $db->sql_fetchassoc($result);
		$cant = $next['count'];
		$db->sql_freeresult($result);
		return ((int) $cant);
	}


	public static function getTipoDocumento(CriterioBusqueda $criterio) { 
		$db = DbManager::getConnection(); 


		$sql = "SELECT * FROM tipodocumento "; 
		$sql .= $criterio->buildFiltro();
		$result = $db->sql_query($sql);
		if (!$result)//hubo un error en la bbdd.
			throw new DBException($db->sql_error());

		if ($db->sql_numrows() > 0) {
			$temp = $db->sql_fetchassoc($result);
			$factory = new TipoDocumentoFactory();
			$obj = $factory->build($temp);
		}
		$db->sql_freeresult($result);
		return $obj;
	}

} 
?>
