<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 05-12-2011
 */
class ConceptoFactory extends GenericFactory {

    public function build($next) {
        $this->setClassName('Concepto');
        $oConcepto = parent::build($next);

        //TODO foreign keys
        if (array_key_exists('ds_tipooperacion', $next)) {
            $tipooperacionFactory = new TipooperacionFactory();
            $oConcepto->setTipooperacion($tipooperacionFactory->build($next));
        }

        if (array_key_exists('ds_tipoconcepto', $next)) {
            $tipoconceptoFactory = new TipoconceptoFactory();
            $oConcepto->setTipoconcepto($tipoconceptoFactory->build($next));
        }


        return $oConcepto;
    }

}
?>
