<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 12-12-2011
 */
class ContactoFactory extends GenericFactory {

    public function build($next) {
        $this->setClassName('Contacto');
        $oContacto = parent::build($next);

        


        return $oContacto;
    }

}
?>
