<?php 

/** 
 * Autogenerated class 
 *  
 *  @author Marcos 
 *  @since 10-10-2018
 */ 
class EmailFactory extends GenericFactory{ 

	public function build($next) { 
		
		$this->setClassName('Email');
		$oEmail = parent::build($next);
		
		 //TODO foreign keys 
		 
		return $oEmail;
	}
} 
?>
