<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 28-10-2011
 */
class EmpleadoFactory extends GenericFactory {

    public function build($next) {
        $this->setClassName('Empleado');
        $oEmpleado = parent::build($next);

        if (array_key_exists('ds_tipodocumento', $next)) {
            $tipodocumentoFactory = new TipoDocumentoFactory();
            $oEmpleado->setTipoDocumento($tipodocumentoFactory->build($next));
        }
        if (array_key_exists('ds_tipopersonal', $next)) {
            $tipopersonalFactory = new TipoPersonalFactory();
            $oEmpleado->setTipoPersonal($tipopersonalFactory->build($next));
        }

        return $oEmpleado;
    }

}
?>
