<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011
 */ 
class InformeFactory extends GenericFactory{ 

	public function build($next) { 
		$this->setClassName('Informe');
		$oInforme = parent::build($next);
		
		 //TODO foreign keys 
		 
		return $oInforme;
	}
} 
?>
