<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 11-01-2012
 */ 
class LiquidacionprofesionalFactory extends GenericFactory{ 

	public function build($next) { 
		$this->setClassName('Liquidacionprofesional');
		$oLiquidacionprofesional = parent::build($next);
		
		 //TODO foreign keys 
		 
		return $oLiquidacionprofesional;
	}
} 
?>
