<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011
 */
class MovcajaconceptoFactory extends GenericFactory {

    public function build($next) {
        $this->setClassName('Movcajaconcepto');
        $oMovcajaconcepto = parent::build($next);

        //TODO foreign keys
        /*if (array_key_exists('cd_practicaordenpractica', $next)) {
            $practicaordenpracticaFactory = new PracticaordenpracticaFactory();
            $oMovcajaconcepto->setPracticaordenpractica($practicaordenpracticaFactory->build($next));
        }*/

        if (array_key_exists('ds_concepto', $next)) {
            $conceptoFactory = new ConceptoFactory();
            $oMovcajaconcepto->setConcepto($conceptoFactory->build($next));
        }

        if (array_key_exists('cd_movcaja', $next)) {
            $movcajaFactory = new MovcajaFactory();
            $oMovcajaconcepto->setMovcaja($movcajaFactory->build($next));
        }
        
        return $oMovcajaconcepto;
    }

}
?>
