<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011
 */
class MovcajacontrolpracticaFactory extends GenericFactory {

    public function build($next) {
        $this->setClassName('Movcajacontrolpractica');
        $oMovcajacontrolpractica = parent::build($next);	

    	if (array_key_exists('ds_obrasocial', $next)) {
            $obrasocialFactory = new ObrasocialFactory();
            $oMovcajacontrolpractica->setObrasocial($obrasocialFactory->build($next));
        }
        
        if (array_key_exists('ds_practica', $next)) {
            $practicaFactory = new PracticaFactory();
            $oMovcajacontrolpractica->setPractica1($practicaFactory->build($next));
        }

    	if (array_key_exists('ds_practica2', $next)) {
            $oPractica = new Practica();
    		$oPractica->setDs_practica($next['ds_practica2']);
            $oMovcajacontrolpractica->setPractica2($oPractica);
        }
        
        return $oMovcajacontrolpractica;
    }

}
?>
