<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 29-06-2011
 */
class MovcajaconceptoNoConflictFactory extends GenericFactory {

    private $alias;

    public function MovcajaconceptoNoConflictFactory($alias="") {
        $this->alias = $alias;
    }

    public function build($next) {
    	
        $oMovcajaconcepto = new Movcajaconcepto();

        $oMovcajaconcepto->setCd_concepto($next[$this->alias . 'cd_concepto']);
        $oMovcajaconcepto->setCd_movcaja($next[$this->alias . 'cd_movcaja']);
        $oMovcajaconcepto->setCd_movcajaconcepto($next[$this->alias . 'cd_movcajaconcepto']);
        $oMovcajaconcepto->setNu_importe($next[$this->alias . 'nu_importe']);
        $oMovcajaconcepto->setBl_tarjeta($next[$this->alias . 'bl_tarjeta']);
        $oMovcajaconcepto->setCd_ordenpractica($next[$this->alias . 'cd_ordenpractica']);

        if (array_key_exists('ds_concepto', $next)) {
            $conceptoFactory = new ConceptoFactory();
            $oMovcajaconcepto->setConcepto($conceptoFactory->build($next));
        }
        if (array_key_exists('cd_practicaordenpractica', $next)) {
            $practicaordenpracticaFactory = new PracticaordenpracticaFactory();
            $oMovcajaconcepto->setPracticaordenpractica($practicaordenpracticaFactory->build($next));
        }
    	/*if (array_key_exists('cd_practicaobrasocial', $next)) {
            $practicaobrasocialFactory = new PracticaobrasocialFactory();
            $oMovcajaconcepto->setPracticaobrasocial($practicaobrasocialFactory->build($next));
        }*/
     	
        return $oMovcajaconcepto;
    }

}
?>
