<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 24-11-2011
 */ 
class ObrasocialFactory extends GenericFactory{ 

	public function build($next) { 
		$this->setClassName('Obrasocial');
		$oObrasocial = parent::build($next);
		
		 //TODO foreign keys 
		 
		return $oObrasocial;
	}
} 
?>
