<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011
 */
class OrdenpracticaFactory extends GenericFactory {

    public function build($next) {
        $this->setClassName('Ordenpractica');
        $oOrdenpractica = parent::build($next);

        if (array_key_exists('ds_obrasocial', $next)) {
            $obrasocialFactory = new ObrasocialFactory();
            $oOrdenpractica->setObrasocial($obrasocialFactory->build($next));
        }

        if (array_key_exists('ds_apynom', $next)) {
            $pacienteFactory = new PacienteFactory();
            $oOrdenpractica->setPaciente($pacienteFactory->build($next));
        }

        if (array_key_exists('ds_nombre', $next)) {
            $profesionalFactory = new ProfesionalFactory();
            $oOrdenpractica->setProfesional($profesionalFactory->build($next));
        }

        if (array_key_exists('dt_movcaja', $next)) {
            $movcajaFactory = new MovcajaFactory();
            $oOrdenpractica->setMovcaja($movcajaFactory->build($next));
        }
        
        return $oOrdenpractica;
    }

}
?>
