<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 24-11-2011
 */ 
class PracticaFactory extends GenericFactory{ 

	public function build($next) { 
		$this->setClassName('Practica');
		$oPractica = parent::build($next);
		
		 //TODO foreign keys 
		 
		return $oPractica;
	}
} 
?>
