<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 24-11-2011
 */
class PracticaobrasocialFactory extends GenericFactory {

    public function build($next) {
        $this->setClassName('Practicaobrasocial');
        $oPracticaobrasocial = parent::build($next);

        //TODO foreign keys
        if (array_key_exists('ds_practica', $next)) {
            $practicaFactory = new PracticaFactory();
            $oPracticaobrasocial->setPractica($practicaFactory->build($next));
        }

        if (array_key_exists('ds_obrasocial', $next)) {
            $obrasocialFactory = new ObrasocialFactory();
            $oPracticaobrasocial->setObrasocial($obrasocialFactory->build($next));
        }


        return $oPracticaobrasocial;
    }

}
?>
