<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 05-12-2011
 */ 
class TipooperacionFactory extends GenericFactory{ 

	public function build($next) { 
		$this->setClassName('Tipooperacion');
		$oTipooperacion = parent::build($next);
		
		 //TODO foreign keys 
		 
		return $oTipooperacion;
	}
} 
?>
