<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 28-10-2011
 */ 
class TipoPersonalFactory extends GenericFactory{ 

	public function build($next) { 
		$this->setClassName('TipoPersonal');
		$oTipoPersonal = parent::build($next);
		
		 //TODO foreign keys 
		 
		return $oTipoPersonal;
	}
} 
?>
