<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 05-12-2011
 */ 
class TipoconceptoFactory extends GenericFactory{ 

	public function build($next) { 
		$this->setClassName('Tipoconcepto');
		$oTipoconcepto = parent::build($next);
		
		 //TODO foreign keys 
		 
		return $oTipoconcepto;
	}
} 
?>
