<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 05-12-2011 
 */ 
class ConceptoManager implements IListar{ 

	public function agregarConcepto(Concepto $oConcepto) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		ConceptoDAO::insertarConcepto($oConcepto);
	}


	public function modificarConcepto(Concepto $oConcepto) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		ConceptoDAO::modificarConcepto($oConcepto);
	}


	public static function eliminarConcepto($id) { 
		//TODO validaciones; 

		$oConcepto = new Concepto();
		$oConcepto->setCd_concepto($id);
		ConceptoDAO::eliminarConcepto($oConcepto);
	}


	public function getConceptos(CriterioBusqueda $criterio) { 
		return ConceptoDAO::getConceptos($criterio); 
	}


	public function getCantConceptos(CriterioBusqueda $criterio) { 
		return ConceptoDAO::getCantConceptos($criterio); 
	}


	public function getConcepto(CriterioBusqueda $criterio) { 
		return ConceptoDAO::getConcepto($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getConceptos($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantConceptos($criterio); 
	}


} 
?>
