<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 12-12-2011 
 */
class ContactoManager implements IListar {

    public function agregarContacto(Contacto $oContacto) {
        //TODO validaciones;
        $this->ValidateOnInsert($oContacto);
        //persistir en la bbdd.
        ContactoDAO::insertarContacto($oContacto);
        
    }

    protected function ValidateOnInsert(Contacto $oContacto) {
        if ($oContacto->getDs_apynom() == "") {
            throw new GenericException("El campo apellido y nombre es obligatorio.");
        }
        

      
    }

    public function modificarContacto(Contacto $oContacto) {
        //TODO validaciones;
        $this->ValidateOnInsert($oContacto);
        //persistir en la bbdd.
        ContactoDAO::modificarContacto($oContacto);

       
    }

    

    public static function eliminarContacto($id) {
        //TODO validaciones;

        $oContacto = new Contacto();
        $oContacto->setCd_contacto($id);
        ContactoDAO::eliminarContacto($oContacto);
    }

    public function getContactos(CriterioBusqueda $criterio) {
        return ContactoDAO::getContactos($criterio);
    }

    public function getCantContactos(CriterioBusqueda $criterio) {
        return ContactoDAO::getCantContactos($criterio);
    }

    public function getContacto(CriterioBusqueda $criterio) {
        return ContactoDAO::getContacto($criterio);
    }

    //	interface IListar
    public function getEntidades(CriterioBusqueda $criterio) {
        return $this->getContactos($criterio);
    }

    public function getCantidadEntidades(CriterioBusqueda $criterio) {
        return $this->getCantContactos($criterio);
    }

}
?>
