<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 28-10-2011 
 */ 
class EmpleadoManager implements IListar{ 

	public function agregarEmpleado(Empleado $oEmpleado) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		EmpleadoDAO::insertarEmpleado($oEmpleado);
	}


	public function modificarEmpleado(Empleado $oEmpleado) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		EmpleadoDAO::modificarEmpleado($oEmpleado);
	}


	public static function eliminarEmpleado($id) { 
		//TODO validaciones; 

		$oEmpleado = new Empleado();
		$oEmpleado->setCd_empleado($id);
		EmpleadoDAO::eliminarEmpleado($oEmpleado);
	}


	public function getEmpleados(CriterioBusqueda $criterio) { 
		return EmpleadoDAO::getEmpleados($criterio); 
	}


	public function getCantEmpleados(CriterioBusqueda $criterio) { 
		return EmpleadoDAO::getCantEmpleados($criterio); 
	}


	public function getEmpleado(CriterioBusqueda $criterio) { 
		return EmpleadoDAO::getEmpleado($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getEmpleados($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantEmpleados($criterio); 
	}


} 
?>
