<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011 
 */ 
class EstadocajaManager implements IListar{ 

	public function agregarEstadocaja(Estadocaja $oEstadocaja) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		EstadocajaDAO::insertarEstadocaja($oEstadocaja);
	}


	public function modificarEstadocaja(Estadocaja $oEstadocaja) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		EstadocajaDAO::modificarEstadocaja($oEstadocaja);
	}


	public static function eliminarEstadocaja($id) { 
		//TODO validaciones; 

		$oEstadocaja = new Estadocaja();
		$oEstadocaja->setCd_estadocaja($id);
		EstadocajaDAO::eliminarEstadocaja($oEstadocaja);
	}


	public function getEstadoscajas(CriterioBusqueda $criterio) { 
		return EstadocajaDAO::getEstadoscajas($criterio); 
	}


	public function getCantEstadoscajas(CriterioBusqueda $criterio) { 
		return EstadocajaDAO::getCantEstadoscajas($criterio); 
	}


	public function getEstadocaja(CriterioBusqueda $criterio) { 
		return EstadocajaDAO::getEstadocaja($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getEstadoscajas($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantEstadoscajas($criterio); 
	}


} 
?>
