<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011 
 */ 
class InformeManager implements IListar{ 

	public function agregarInforme(Informe $oInforme) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		InformeDAO::insertarInforme($oInforme);
	}


	public function modificarInforme(Informe $oInforme) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		InformeDAO::modificarInforme($oInforme);
	}


	public static function eliminarInforme($id) { 
		//TODO validaciones; 

		$oInforme = new Informe();
		$oInforme->setCd_informe($id);
		InformeDAO::eliminarInforme($oInforme);
	}


	public function getInformes(CriterioBusqueda $criterio) { 
		return InformeDAO::getInformes($criterio); 
	}


	public function getCantInformes(CriterioBusqueda $criterio) { 
		return InformeDAO::getCantInformes($criterio); 
	}


	public function getInforme(CriterioBusqueda $criterio) { 
		return InformeDAO::getInforme($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getInformes($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantInformes($criterio); 
	}


} 
?>
