<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 11-01-2012 
 */ 
class LiquidacionprofesionalManager implements IListar{ 

	public function agregarLiquidacionprofesional(Liquidacionprofesional $oLiquidacionprofesional) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		LiquidacionprofesionalDAO::insertarLiquidacionprofesional($oLiquidacionprofesional);
	}


	public function modificarLiquidacionprofesional(Liquidacionprofesional $oLiquidacionprofesional) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		LiquidacionprofesionalDAO::modificarLiquidacionprofesional($oLiquidacionprofesional);
	}


	public static function eliminarLiquidacionprofesional($id) { 
		//TODO validaciones; 

		$oLiquidacionprofesional = new Liquidacionprofesional();
		$oLiquidacionprofesional->setCd_liquidacionprofesional($id);
		LiquidacionprofesionalDAO::eliminarLiquidacionprofesional($oLiquidacionprofesional);
	}


	public function getLiquidacionprofesionales(CriterioBusqueda $criterio) { 
		return LiquidacionprofesionalDAO::getLiquidacionprofesionales($criterio); 
	}


	public function getCantLiquidacionprofesionales(CriterioBusqueda $criterio) { 
		return LiquidacionprofesionalDAO::getCantLiquidacionprofesionales($criterio); 
	}


	public function getLiquidacionprofesional(CriterioBusqueda $criterio) { 
		return LiquidacionprofesionalDAO::getLiquidacionprofesional($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getLiquidacionprofesionales($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantLiquidacionprofesionales($criterio); 
	}


} 
?>
