<?php

/**
 * Autogenerated class
 *
 *  @author modelBuilder
 *  @since 18-05-2021
 */
class MedioManager implements IListar{

	public function agregarMedio(Medio $oMedio) {
		//TODO validaciones;

		//persistir en la bbdd.
		MedioDAO::insertarMedio($oMedio);
	}


	public function modificarMedio(Medio $oMedio) {
		//TODO validaciones;

		//persistir en la bbdd.
		MedioDAO::modificarMedio($oMedio);
	}


	public static function eliminarMedio($id) {
		//TODO validaciones;

		$oMedio = new Medio();
		$oMedio->setCd_medio($id);
		MedioDAO::eliminarMedio($oMedio);
	}


	public function getMedios(CriterioBusqueda $criterio) {
		return MedioDAO::getMedios($criterio);
	}


	public function getCantMedios(CriterioBusqueda $criterio) {
		return MedioDAO::getCantMedios($criterio);
	}


	public function getMedio(CriterioBusqueda $criterio) {
		return MedioDAO::getMedio($criterio);
	}

	//	interface IListar
	public function getEntidades(CriterioBusqueda $criterio) {
		return $this->getMedios($criterio);
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) {
		return $this->getCantMedios($criterio);
	}


}
?>
