<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011 
 */ 
class MovcajacontrolpracticaManager implements IListar{ 

	


	public function getMovcajacontrolpracticas($cd_obrasocial, $cd_practica1, $cd_practica2) { 
		return MovcajacontrolpracticaDAO::getMovcajacontrolpracticas($cd_obrasocial, $cd_practica1, $cd_practica2); 
	}

        


	public function getCantMovcajacontrolpracticas(CriterioBusqueda $criterio) { 
		return MovcajacontrolpracticaDAO::getCantMovcajacontrolpracticas($criterio); 
	}


	public function getMovcajacontrolpractica(CriterioBusqueda $criterio) { 
		return MovcajacontrolpracticaDAO::getMovcajacontrolpractica($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getMovcajacontrolpracticas($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantMovcajacontrolpracticas($criterio); 
	}


} 
?>
