<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011 
 */ 
class MovcajaconceptoManager implements IListar{ 

	public function agregarMovcajaconcepto(Movcajaconcepto $oMovcajaconcepto) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		MovcajaconceptoDAO::insertarMovcajaconcepto($oMovcajaconcepto);
	}


	public function modificarMovcajaconcepto(Movcajaconcepto $oMovcajaconcepto) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		MovcajaconceptoDAO::modificarMovcajaconcepto($oMovcajaconcepto);
	}


	public static function eliminarMovcajaconcepto($id) { 
		//TODO validaciones; 

		$oMovcajaconcepto = new Movcajaconcepto();
		$oMovcajaconcepto->setCd_movcajaconcepto($id);
		MovcajaconceptoDAO::eliminarMovcajaconcepto($oMovcajaconcepto);
	}


	public function getMovcajaconceptos(CriterioBusqueda $criterio) { 
		return MovcajaconceptoDAO::getMovcajaconceptos($criterio); 
	}

        public function getMovcajaconceptosDeObraSocial(CriterioBusqueda $criterio) { 
		return MovcajaconceptoDAO::getMovcajaconceptosDeObraSocial($criterio); 
	}


	public function getCantMovcajaconceptos(CriterioBusqueda $criterio) { 
		return MovcajaconceptoDAO::getCantMovcajaconceptos($criterio); 
	}


	public function getMovcajaconcepto(CriterioBusqueda $criterio) { 
		return MovcajaconceptoDAO::getMovcajaconcepto($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getMovcajaconceptos($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantMovcajaconceptos($criterio); 
	}
	
	public static function eliminarMovcajaconceptoPorMovcaja($cd_movcaja) { 
		//TODO validaciones; 
		MovcajaconceptoDAO::eliminarMovcajaconceptoPorMovcaja($cd_movcaja);
	}


} 
?>
