<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 24-11-2011 
 */ 
class ObrasocialManager implements IListar{ 

	public function agregarObrasocial(Obrasocial $oObrasocial) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		ObrasocialDAO::insertarObrasocial($oObrasocial);
	}


	public function modificarObrasocial(Obrasocial $oObrasocial) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		ObrasocialDAO::modificarObrasocial($oObrasocial);
	}


	public static function eliminarObrasocial($id) { 
		//TODO validaciones; 

		$oObrasocial = new Obrasocial();
		$oObrasocial->setCd_obrasocial($id);
		ObrasocialDAO::eliminarObrasocial($oObrasocial);
	}


	public function getObrasociales(CriterioBusqueda $criterio) { 
		return ObrasocialDAO::getObrasociales($criterio); 
	}


	public function getCantObrasociales(CriterioBusqueda $criterio) { 
		return ObrasocialDAO::getCantObrasociales($criterio); 
	}


	public function getObrasocial(CriterioBusqueda $criterio) { 
		return ObrasocialDAO::getObrasocial($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getObrasociales($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantObrasociales($criterio); 
	}


} 
?>
