<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 24-11-2011 
 */ 
class PracticaobrasocialManager implements IListar{ 

	public function agregarPracticaobrasocial(Practicaobrasocial $oPracticaobrasocial) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		PracticaobrasocialDAO::insertarPracticaobrasocial($oPracticaobrasocial);
	}


	public function modificarPracticaobrasocial(Practicaobrasocial $oPracticaobrasocial) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		PracticaobrasocialDAO::modificarPracticaobrasocial($oPracticaobrasocial);
	}

        public function modificarRepeticionesDePracticaobrasocial(Practicaobrasocial $oPracticaobrasocial) {
		//TODO validaciones;

		//persistir en la bbdd.
		PracticaobrasocialDAO::modificarRepeticionesDePracticaobrasocial($oPracticaobrasocial);
	}


	public static function eliminarPracticaobrasocial($id) { 
		//TODO validaciones; 

		$oPracticaobrasocial = new Practicaobrasocial();
		$oPracticaobrasocial->setCd_practicaobrasocial($id);
		PracticaobrasocialDAO::eliminarPracticaobrasocial($oPracticaobrasocial);
	}


	public function getPracticaobrasociales(CriterioBusqueda $criterio) { 
		return PracticaobrasocialDAO::getPracticaobrasociales($criterio); 
	}


	public function getCantPracticaobrasociales(CriterioBusqueda $criterio) { 
		return PracticaobrasocialDAO::getCantPracticaobrasociales($criterio); 
	}


	public function getPracticaobrasocial(CriterioBusqueda $criterio) { 
		return PracticaobrasocialDAO::getPracticaobrasocial($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getPracticaobrasociales($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantPracticaobrasociales($criterio); 
	}


} 
?>
