<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 24-11-2011 
 */ 
class PracticaManager implements IListar{ 

	public function agregarPractica(Practica $oPractica) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		PracticaDAO::insertarPractica($oPractica);
	}


	public function modificarPractica(Practica $oPractica) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		PracticaDAO::modificarPractica($oPractica);
	}


	public static function eliminarPractica($id) { 
		//TODO validaciones; 

		$oPractica = new Practica();
		$oPractica->setCd_practica($id);
		PracticaDAO::eliminarPractica($oPractica);
	}


	public function getPracticas(CriterioBusqueda $criterio) { 
		return PracticaDAO::getPracticas($criterio); 
	}


	public function getCantPracticas(CriterioBusqueda $criterio) { 
		return PracticaDAO::getCantPracticas($criterio); 
	}


	public function getPractica(CriterioBusqueda $criterio) { 
		return PracticaDAO::getPractica($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getPracticas($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantPracticas($criterio); 
	}


} 
?>
