<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011 
 */
class PracticaordenpracticaManager implements IListar {

    public function agregarPracticaordenpractica(Practicaordenpractica $oPracticaordenpractica) {
        //TODO validaciones;
        //persistir en la bbdd.
        PracticaordenpracticaDAO::insertarPracticaordenpractica($oPracticaordenpractica);
    }

    public function modificarPracticaordenpractica(Practicaordenpractica $oPracticaordenpractica) {
        //TODO validaciones;
        //persistir en la bbdd.
        PracticaordenpracticaDAO::modificarPracticaordenpractica($oPracticaordenpractica);
    }

    public static function eliminarPracticaordenpractica($id) {
        //TODO validaciones;

        $oPracticaordenpractica = new Practicaordenpractica();
        $oPracticaordenpractica->setCd_practicaordenpractica($id);
        PracticaordenpracticaDAO::eliminarPracticaordenpractica($oPracticaordenpractica);
    }

    public function getPracticaordenpracticas(CriterioBusqueda $criterio) {

        return PracticaordenpracticaDAO::getPracticaordenpracticas($criterio);
    }

    public function getPracticaordenpracticasTablemodel(CriterioBusqueda $criterio) {

        return PracticaordenpracticaDAO::getPracticaordenpracticasTablemodel($criterio);
    }

    public function getCantPracticaordenpracticasTableModel(CriterioBusqueda $criterio) {
        return PracticaordenpracticaDAO::getCantPracticaordenpracticasTableModel($criterio);
    }

    public function getPracticaordenpracticasConsumidas(CriterioBusqueda $criterio) {

        return PracticaordenpracticaDAO::getPracticaordenpracticasConsumidas($criterio);
    }

    public function getPracticaordenpracticasDeLiquidacion(CriterioBusqueda $criterio, $valor = 0, $tipo="f") {
        return PracticaordenpracticaDAO::getPracticaordenpracticasDeLiquidacion($criterio, $valor, $tipo);
    }

    public function getTotalALiquidar(CriterioBusqueda $criterio, $valor = 0, $tipo="f") {
        return PracticaordenpracticaDAO::getTotalALiquidar($criterio, $valor, $tipo);
    }

    public function getTotalPlacas(CriterioBusqueda $criterio) {
        return PracticaordenpracticaDAO::getTotalPlacas($criterio);
    }
    
	public function getTotalMontoPlacas(CriterioBusqueda $criterio) {
        return PracticaordenpracticaDAO::getTotalMontoPlacas($criterio);
    }

    public function getTotalPacientes(CriterioBusqueda $criterio) {
        return PracticaordenpracticaDAO::getTotalPacientes($criterio);
    }

    public function getTotalPlacasPorPractica(CriterioBusqueda $criterio) {
        return PracticaordenpracticaDAO::getTotalPlacasPorPractica($criterio);
    }

    public function getCantPracticaordenpracticas(CriterioBusqueda $criterio) {
        return PracticaordenpracticaDAO::getCantPracticaordenpracticas($criterio);
    }

    public function getPracticaordenpractica(CriterioBusqueda $criterio) {
        return PracticaordenpracticaDAO::getPracticaordenpractica($criterio);
    }

    //	interface IListar
    public function getEntidades(CriterioBusqueda $criterio) {
        return $this->getPracticaordenpracticas($criterio);
    }

    public function getCantidadEntidades(CriterioBusqueda $criterio) {
        return $this->getCantPracticaordenpracticas($criterio);
    }

    public function modificarPrecioPracticasObraSocial( Practicaobrasocial $oPracticaobrasocial ){
    	
    	//recupero todas las practicas de la obra social realizadas dada la fecha de vigencia
    	
    	$dt_vigencia = $oPracticaobrasocial->getDt_vigencia();
    	$cd_obrasocial = $oPracticaobrasocial->getCd_obrasocial();
    	$cd_practica = $oPracticaobrasocial->getCd_practica();
    	
    	$items = PracticaordenpracticaDAO::getPracticaordenpracticasByPracticaObraSocialDtVigencia($cd_practica, $cd_obrasocial, $dt_vigencia);
    	
    	$ids = array();
    	$movcajasconcepto = array();
    	
    	foreach ($items as $oPracticaordenpractica) {
    		
    		$ids[] = $oPracticaordenpractica->getCd_practicaordenpractica();
    		
    		$movcajasconcepto[] = $oPracticaordenpractica->getCd_movcajaconcepto();
    		
    	}
    	
    	if( count($ids) > 0 ){
			
    		PracticaordenpracticaDAO::modificarPracticaObraSocial( $ids, $oPracticaobrasocial->getCd_practicaobrasocial() );
    	
    		MovcajaconceptoDAO::modificarImportes( $movcajasconcepto, $oPracticaobrasocial->getNu_importe() );
    		
    	}
    	    	
    }
    
	public static function eliminarPracticaordenpracticaPorOrdenpractica($cd_ordenpractica) {
        //TODO validaciones;

        PracticaordenpracticaDAO::eliminarPracticaordenpracticaPorOrdenpractica($cd_ordenpractica);
    }
}
?>
