<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011 
 */ 
class ProcesocajaManager implements IListar{ 

	public function agregarProcesocaja(Procesocaja $oProcesocaja) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		ProcesocajaDAO::insertarProcesocaja($oProcesocaja);
	}


	public function modificarProcesocaja(Procesocaja $oProcesocaja) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		ProcesocajaDAO::modificarProcesocaja($oProcesocaja);
	}


	public static function eliminarProcesocaja($id) { 
		//TODO validaciones; 

		$oProcesocaja = new Procesocaja();
		$oProcesocaja->setCd_procesocaja($id);
		ProcesocajaDAO::eliminarProcesocaja($oProcesocaja);
	}


	public function getProcesoscajas(CriterioBusqueda $criterio) { 
		return ProcesocajaDAO::getProcesoscajas($criterio); 
	}


	public function getCantProcesoscajas(CriterioBusqueda $criterio) { 
		return ProcesocajaDAO::getCantProcesoscajas($criterio); 
	}


	public function getProcesocaja(CriterioBusqueda $criterio) { 
		return ProcesocajaDAO::getProcesocaja($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getProcesoscajas($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantProcesoscajas($criterio); 
	}


} 
?>
