<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 28-10-2011 
 */ 
class ProfesionalManager implements IListar{ 

	public function agregarProfesional(Profesional $oProfesional) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		ProfesionalDAO::insertarProfesional($oProfesional);
	}


	public function modificarProfesional(Profesional $oProfesional) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		ProfesionalDAO::modificarProfesional($oProfesional);
	}


	public static function eliminarProfesional($id) { 
		//TODO validaciones; 

		$oProfesional = new Profesional();
		$oProfesional->setCd_profesional($id);
		ProfesionalDAO::eliminarProfesional($oProfesional);
	}


	public function getProfesionales(CriterioBusqueda $criterio) { 
		return ProfesionalDAO::getProfesionales($criterio); 
	}


	public function getCantProfesionales(CriterioBusqueda $criterio) { 
		return ProfesionalDAO::getCantProfesionales($criterio); 
	}


	public function getProfesional(CriterioBusqueda $criterio) { 
		return ProfesionalDAO::getProfesional($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getProfesionales($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantProfesionales($criterio); 
	}


} 
?>
