<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 28-10-2011 
 */ 
class TipoPersonalManager implements IListar{ 

	public function agregarTipoPersonal(TipoPersonal $oTipoPersonal) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		TipoPersonalDAO::insertarTipoPersonal($oTipoPersonal);
	}


	public function modificarTipoPersonal(TipoPersonal $oTipoPersonal) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		TipoPersonalDAO::modificarTipoPersonal($oTipoPersonal);
	}


	public static function eliminarTipoPersonal($id) { 
		//TODO validaciones; 

		$oTipoPersonal = new TipoPersonal();
		$oTipoPersonal->setCd_tipopersonal($id);
		TipoPersonalDAO::eliminarTipoPersonal($oTipoPersonal);
	}


	public function getTipoPersonales(CriterioBusqueda $criterio) { 
		return TipoPersonalDAO::getTipoPersonales($criterio); 
	}


	public function getCantTipoPersonales(CriterioBusqueda $criterio) { 
		return TipoPersonalDAO::getCantTipoPersonales($criterio); 
	}


	public function getTipoPersonal(CriterioBusqueda $criterio) { 
		return TipoPersonalDAO::getTipoPersonal($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getTipoPersonales($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantTipoPersonales($criterio); 
	}


} 
?>
