<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 05-12-2011 
 */ 
class TipoconceptoManager implements IListar{ 

	public function agregarTipoconcepto(Tipoconcepto $oTipoconcepto) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		TipoconceptoDAO::insertarTipoconcepto($oTipoconcepto);
	}


	public function modificarTipoconcepto(Tipoconcepto $oTipoconcepto) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		TipoconceptoDAO::modificarTipoconcepto($oTipoconcepto);
	}


	public static function eliminarTipoconcepto($id) { 
		//TODO validaciones; 

		$oTipoconcepto = new Tipoconcepto();
		$oTipoconcepto->setCd_tipoconcepto($id);
		TipoconceptoDAO::eliminarTipoconcepto($oTipoconcepto);
	}


	public function getTipoconceptos(CriterioBusqueda $criterio) { 
		return TipoconceptoDAO::getTipoconceptos($criterio); 
	}


	public function getCantTipoconceptos(CriterioBusqueda $criterio) { 
		return TipoconceptoDAO::getCantTipoconceptos($criterio); 
	}


	public function getTipoconcepto(CriterioBusqueda $criterio) { 
		return TipoconceptoDAO::getTipoconcepto($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getTipoconceptos($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantTipoconceptos($criterio); 
	}


} 
?>
