<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011 
 */ 
class TurnoManager implements IListar{ 

	public function agregarTurno(Turno $oTurno) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		TurnoDAO::insertarTurno($oTurno);
	}


	public function modificarTurno(Turno $oTurno) { 
		//TODO validaciones; 

		//persistir en la bbdd.
		TurnoDAO::modificarTurno($oTurno);
	}


	public static function eliminarTurno($id) { 
		//TODO validaciones; 

		$oTurno = new Turno();
		$oTurno->setCd_turno($id);
		TurnoDAO::eliminarTurno($oTurno);
	}


	public function getTurnos(CriterioBusqueda $criterio) { 
		return TurnoDAO::getTurnos($criterio); 
	}


	public function getCantTurnos(CriterioBusqueda $criterio) { 
		return TurnoDAO::getCantTurnos($criterio); 
	}


	public function getTurno(CriterioBusqueda $criterio) { 
		return TurnoDAO::getTurno($criterio); 
	}

	//	interface IListar 
	public function getEntidades(CriterioBusqueda $criterio) { 
		return $this->getTurnos($criterio); 
	}


	public function getCantidadEntidades(CriterioBusqueda $criterio) { 
		return $this->getCantTurnos($criterio); 
	}


} 
?>
