<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011 
 */
class ArqueoCajaExcelTableModel extends ListarTableModel {

    private $columnNames = array();
    private $columnWidths = array();

    public function ArqueoCajaExcelTableModel(ItemCollection $items) {
        $this->items = $items;
        $this->initColumns();
    }

    private function initColumns() {
        

        $this->columnNames[] = RYT_MOVCAJA_DT_MOVCAJA;
        $this->columnWidths[] = 60;

        $this->columnNames[] = RYT_MOVCAJA_NU_TOTAL;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_MOVCAJA_DS_DETALLE;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_MOVCAJA_DS_PACIENTE;
        $this->columnWidths[] = 100;
        
        $this->columnNames[] = RYT_MOVCAJA_NU_ETIQUETA_SIMPLE;
        $this->columnWidths[] = 40;
        
        
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
     */
    function getTitle() {
        return "Movcajas";
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
     */
    function getColumnCount() {
        return count($this->columnNames);
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
     */
    function getColumnName($columnIndex) {
        return $this->columnNames[$columnIndex];
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
     */
    function getColumnWidth($columnIndex) {
        return $this->columnWidths[$columnIndex];
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
     */
    function getRowCount() {
        $this->items->size();
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
     */
    function getValueAt($rowIndex, $columnIndex) {
        $oObject = $this->items->getObjectByIndex($rowIndex);
        return $this->getValue($oObject, $columnIndex);
    }

    public function getValue($anObject, $columnIndex) {
        $oMovcaja = $anObject;
        $value = 0;
        switch ($columnIndex) {

            
            case 0: $value = "<p style='text-align:left; font-size:27px; font-family:arial'>".FuncionesComunes::fechaHoraMysqlaPHP($oMovcaja->getDt_movcaja())."</p>";
                break;
            case 1: $value = "<p style='text-align:left; font-size:27px; font-family:arial'>".$oMovcaja->getNu_total()."</p>";
                break;
            case 2: 
            	$detalle = str_replace("<ul>","",$oMovcaja->getDs_detalle());
            	$detalle = str_replace("<li>","<p style='text-align:left; font-size:27px; font-family:arial'>",$detalle);
            	$detalle = str_replace("</li>","</p>",$detalle);
            	$detalle = str_replace("</ul>","",$detalle);
            	$value = trim($detalle);
                break;
            case 3: $value = "<p style='text-align:left; font-size:27px; font-family:arial'>".$oMovcaja->getDs_paciente()."</p>";
                break;
            case 4: $value = "<p style='text-align:left; font-size:27px; font-family:arial'>".$oMovcaja->getNu_etiquetasimple()."</p>";;
                break;
            
            default: $value = '';
                break;
        }
        return $value;
    }

    public function getEncabezados() {

        
        $encabezados[] = $this->buildTh($this->getColumnName(0), 'dt_movcaja', 'dt_movcaja');
        $encabezados[] = $this->buildTh($this->getColumnName(1), 'nu_total', 'nu_total');
        $encabezados[] = $this->buildTh($this->getColumnName(2), 'ds_detalle', 'ds_detalle');
        $encabezados[] = $this->buildTh($this->getColumnName(3), 'ds_paciente', 'ds_paciente');
        $encabezados[] = $this->buildTh($this->getColumnName(4), 'nu_etiquetasimple', 'nu_etiquetasimple');
        
        return $encabezados;
    }

}
?>
