<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 05-12-2011 
 */ 
class ConceptoTableModel extends ListarTableModel{

	private $columnNames = array();

	private $columnWidths = array();
	
	public function ConceptoTableModel(ItemCollection $items){
		$this->items = $items;
		$this->initColumns();
	}
	
	private function initColumns(){
			
		$this->columnNames[] = RYT_CONCEPTO_CD_TIPOCONCEPTO;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = RYT_CONCEPTO_CD_TIPOOPERACION;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = RYT_CONCEPTO_DS_CONCEPTO;
		$this->columnWidths[] = 80;
		
	}
	
		
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
	 */
	function getTitle(){
		return "Conceptos";
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
	 */
	function getColumnCount(){
		return count($this->columnNames);
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
	 */
	function getColumnName($columnIndex){
		return $this->columnNames[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
	 */
	function getColumnWidth($columnIndex){
		return $this->columnWidths[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
	 */
	function getRowCount(){
		$this->items->size();
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
	 */
	function getValueAt($rowIndex, $columnIndex){
		$oObject = $this->items->getObjectByIndex($rowIndex);
		return $this->getValue($oObject, $columnIndex);
	}

	public function getValue($anObject, $columnIndex){
		$oConcepto = $anObject;
		$value=0;
		switch ($columnIndex) {			
			case 0: $value= $oConcepto->getTipoconcepto()->getDs_tipoconcepto(); break;
			case 1: $value= $oConcepto->getTipooperacion()->getDs_tipooperacion(); break;
			case 2: $value= $oConcepto->getDs_concepto(); break;
			default: $value='';	break;
		}
		return $value;
	}
	
	public function getEncabezados(){
	 	$encabezados[]= $this->buildTh($this->getColumnName(0), 'TC.ds_tipoconcepto', 'Tipo de concepto');
	 	$encabezados[]= $this->buildTh($this->getColumnName(1), 'T_O.ds_tipooperacion', 'Tipo de operacion');
	 	$encabezados[]= $this->buildTh($this->getColumnName(2), 'C.ds_concepto', 'Concepto');
	 	return $encabezados;	
	}
	
}
?>
