<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 12-12-2011 
 */
class ContactoTableModel extends ListarTableModel {

    private $columnNames = array();
    private $columnWidths = array();

    public function ContactoTableModel(ItemCollection $items) {
        $this->items = $items;
        $this->initColumns();
    }

    private function initColumns() {

        $this->columnNames[] = RYT_CONTACTO_CD_CONTACTO;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_CONTACTO_DS_APYNOM;
        $this->columnWidths[] = 80;
        
        $this->columnNames[] = RYT_CONTACTO_NU_DOCUMENTO;
        $this->columnWidths[] = 80;
        
        $this->columnNames[] = RYT_CONTACTO_NU_CUIT;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_CONTACTO_DS_TELEFONO;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_CONTACTO_DS_MOVIL;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_CONTACTO_DS_DIRECCION;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_CONTACTO_DS_EMAIL;
        $this->columnWidths[] = 80;
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
     */
    function getTitle() {
        return "Contactos";
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
     */
    function getColumnCount() {
        return count($this->columnNames);
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
     */
    function getColumnName($columnIndex) {
        return $this->columnNames[$columnIndex];
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
     */
    function getColumnWidth($columnIndex) {
        return $this->columnWidths[$columnIndex];
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
     */
    function getRowCount() {
        $this->items->size();
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
     */
    function getValueAt($rowIndex, $columnIndex) {
        $oObject = $this->items->getObjectByIndex($rowIndex);
        return $this->getValue($oObject, $columnIndex);
    }

    public function getValue($anObject, $columnIndex) {
        $oContacto = $anObject;
        $value = 0;
        switch ($columnIndex) {

            case 0: $value = $oContacto->getCd_contacto();
                break;

            case 1: $value = $oContacto->getDs_apynom();
                break;

            case 2: $value = $oContacto->getNu_documento();
                break;

            case 3: $value = $oContacto->getNu_cuit();
                break;
                
            case 4: $value = $oContacto->getDs_telefono();
                break;

            case 5: $value = $oContacto->getDs_movil();
                break;

            case 6: $value = $oContacto->getDs_direccion();
                break;

            case 7: $value = $oContacto->getDs_email();
                break;

            default: $value = '';
                break;
        }
        return $value;
    }

    public function getEncabezados() {

        $encabezados[] = $this->buildTh($this->getColumnName(0), 'cd_contacto', 'cd_contacto');

        $encabezados[] = $this->buildTh($this->getColumnName(1), 'ds_apynom', 'ds_apynom');

        $encabezados[] = $this->buildTh($this->getColumnName(2), 'nu_documento', 'nu_documento');

        $encabezados[] = $this->buildTh($this->getColumnName(3), 'nu_cuit', 'nu_cuit');
        
        $encabezados[] = $this->buildTh($this->getColumnName(4), 'ds_telefono', 'ds_telefono');

        $encabezados[] = $this->buildTh($this->getColumnName(5), 'ds_movil', 'ds_movil');

        $encabezados[] = $this->buildTh($this->getColumnName(6), 'ds_direccion', 'ds_direccion');

        $encabezados[] = $this->buildTh($this->getColumnName(7), 'ds_email', 'ds_email');

        return $encabezados;
    }

}
?>
