<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 15-03-2018 
 */
class CumpleTableModel extends ListarTableModel {

    private $columnNames = array();
    private $columnWidths = array();

    public function CumpleTableModel(ItemCollection $items) {
        $this->items = $items;
        $this->initColumns();
    }

    private function initColumns() {

        $this->columnNames[] = RYT_PACIENTE_CD_PACIENTE;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_PACIENTE_DS_APYNOM;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_PACIENTE_DT_PACIENTE;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_PACIENTE_DS_TELEFONO;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_PACIENTE_DS_EMAIL;
        $this->columnWidths[] = 80;
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
     */
    function getTitle() {
        return "Cumplea&ntilde;os";
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
     */
    function getColumnCount() {
        return count($this->columnNames);
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
     */
    function getColumnName($columnIndex) {
        return $this->columnNames[$columnIndex];
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
     */
    function getColumnWidth($columnIndex) {
        return $this->columnWidths[$columnIndex];
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
     */
    function getRowCount() {
        $this->items->size();
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
     */
    function getValueAt($rowIndex, $columnIndex) {
        $oObject = $this->items->getObjectByIndex($rowIndex);
        return $this->getValue($oObject, $columnIndex);
    }

    public function getValue($anObject, $columnIndex) {
        $oPaciente = $anObject;
        $value = 0;
        switch ($columnIndex) {

            case 0: $value = $oPaciente->getCd_paciente();
                break;

            case 1: $value = $oPaciente->getDs_apynom();
                break;

            case 2: $value = FuncionesComunes::fechaMysqlaPHP($oPaciente->getDt_nacimiento());
                break;

            case 3: $value = $oPaciente->getDs_telefono();
                break;

            case 4: $value = $oPaciente->getDs_email();
                break;

            default: $value = '';
                break;
        }
        return $value;
    }

    public function getEncabezados() {

        $encabezados[] = $this->buildTh($this->getColumnName(0), 'cd_paciente', 'cd_paciente');

        $encabezados[] = $this->buildTh($this->getColumnName(1), 'ds_apynom', 'ds_apynom');

        $encabezados[] = $this->buildTh($this->getColumnName(2), 'dt_nacimiento', 'dt_nacimiento');
        
        $encabezados[] = $this->buildTh($this->getColumnName(3), 'ds_telefono', 'ds_telefono');

        $encabezados[] = $this->buildTh($this->getColumnName(4), 'ds_email', 'ds_email');

        return $encabezados;
    }

}
?>
