<?php 

/** 
 * Autogenerated class 
 *  
 *  @author Marcos 
 *  @since 10-10-2018 
 */ 
class EmailTableModel extends ListarTableModel{

	private $columnNames = array();

	private $columnWidths = array();
	
	public function EmailTableModel(ItemCollection $items){
		$this->items = $items;
		$this->initColumns();
	}
	
	private function initColumns(){
		
		$this->columnNames[] = RYT_EMAIL_CD_EMAIL;
		$this->columnWidths[] = 20;
		
		$this->columnNames[] = RYT_EMAIL_DT_FECHA;
		$this->columnWidths[] = 30;
		
		$this->columnNames[] = RYT_EMAIL_DS_ASUNTO;
		$this->columnWidths[] = 50;
		
	}
	
		
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
	 */
	function getTitle(){
		return "Emails";
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
	 */
	function getColumnCount(){
		return count($this->columnNames);
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
	 */
	function getColumnName($columnIndex){
		return $this->columnNames[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
	 */
	function getColumnWidth($columnIndex){
		return $this->columnWidths[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
	 */
	function getRowCount(){
		$this->items->size();
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
	 */
	function getValueAt($rowIndex, $columnIndex){
		$oObject = $this->items->getObjectByIndex($rowIndex);
		return $this->getValue($oObject, $columnIndex);
	}

	public function getValue($anObject, $columnIndex){
		$oEmail = $anObject;
		$value=0;
		switch ($columnIndex) {
			
			case 0: $value= $oEmail->getCd_email(); break;
			
			case 1: $value= $oEmail->getDt_fecha(); break;
			
			case 2: $value= $oEmail->getDs_asunto(); break;
			
			default: $value='';	break;
		}
		return $value;
	}
	
	public function getEncabezados(){
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(0), 'cd_email', 'cd_email');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(1), 'dt_fecha', 'dt_fecha');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(2), 'ds_asunto', 'ds_asunto');
	 	
	 	return $encabezados;	
	}
	
}
?>
