<?php

/**
 * Autogenerated class
 *
 *  @author modelBuilder
 *  @since 18-05-2021
 */
class MedioTableModel extends ListarTableModel{

	private $columnNames = array();

	private $columnWidths = array();

	public function MedioTableModel(ItemCollection $items){
		$this->items = $items;
		$this->initColumns();
	}

	private function initColumns(){

		$this->columnNames[] = RYT_MEDIO_CD_MEDIO;
		$this->columnWidths[] = 80;

		$this->columnNames[] = RYT_MEDIO_DS_MEDIO;
		$this->columnWidths[] = 80;

	}


	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
	 */
	function getTitle(){
		return "Medios";
	}

	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
	 */
	function getColumnCount(){
		return count($this->columnNames);
	}

	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
	 */
	function getColumnName($columnIndex){
		return $this->columnNames[$columnIndex];
	}

	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
	 */
	function getColumnWidth($columnIndex){
		return $this->columnWidths[$columnIndex];
	}

	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
	 */
	function getRowCount(){
		$this->items->size();
	}

	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
	 */
	function getValueAt($rowIndex, $columnIndex){
		$oObject = $this->items->getObjectByIndex($rowIndex);
		return $this->getValue($oObject, $columnIndex);
	}

	public function getValue($anObject, $columnIndex){
		$oMedio = $anObject;
		$value=0;
		switch ($columnIndex) {

			case 0: $value= $oMedio->getCd_medio(); break;

			case 1: $value= $oMedio->getDs_medio(); break;

			default: $value='';	break;
		}
		return $value;
	}

	public function getEncabezados(){

	 	$encabezados[]= $this->buildTh($this->getColumnName(0), 'cd_medio', 'cd_medio');

	 	$encabezados[]= $this->buildTh($this->getColumnName(1), 'ds_medio', 'ds_medio');

	 	return $encabezados;
	}

}
?>
