<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011 
 */
class MovcajaTableModel extends ListarTableModel {

    private $columnNames = array();
    private $columnWidths = array();

    public function MovcajaTableModel(ItemCollection $items) {
        $this->items = $items;
        $this->initColumns();
    }

    private function initColumns() {
        $this->columnNames[] = RYT_MOVCAJA_CD_MOVCAJA;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_MOVCAJA_DT_MOVCAJA;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_MOVCAJA_NU_TOTAL;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_MOVCAJA_DS_DETALLE;
        $this->columnWidths[] = 80;
        
        $this->columnNames[] = RYT_MOVCAJA_DS_PACIENTE;
        $this->columnWidths[] = 80;
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
     */
    function getTitle() {
        return "Movcajas";
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
     */
    function getColumnCount() {
        return count($this->columnNames);
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
     */
    function getColumnName($columnIndex) {
        return $this->columnNames[$columnIndex];
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
     */
    function getColumnWidth($columnIndex) {
        return $this->columnWidths[$columnIndex];
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
     */
    function getRowCount() {
        $this->items->size();
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
     */
    function getValueAt($rowIndex, $columnIndex) {
        $oObject = $this->items->getObjectByIndex($rowIndex);
        return $this->getValue($oObject, $columnIndex);
    }

    public function getValue($anObject, $columnIndex) {
        $oMovcaja = $anObject;
        $value = 0;
        switch ($columnIndex) {

            case 0: $value = $oMovcaja->getCd_movcaja();
                break;
            case 1: $value = FuncionesComunes::fechaHoraMysqlaPHP($oMovcaja->getDt_movcaja());
                break;
            case 2: $value = $oMovcaja->getNu_total();
                break;
            case 3: $value = $oMovcaja->getDs_detalle();
                break;
            case 4: $value = $oMovcaja->getDs_paciente();
                break;
            default: $value = '';
                break;
        }
        return $value;
    }

    public function getEncabezados() {

        $encabezados[] = $this->buildTh($this->getColumnName(0), 'MC.cd_movcaja', 'cd_movcaja');
        $encabezados[] = $this->buildTh($this->getColumnName(1), 'dt_movcaja', 'dt_movcaja');
        $encabezados[] = $this->buildTh($this->getColumnName(2), null, null);
        $encabezados[] = $this->buildTh($this->getColumnName(3), null, null);
        $encabezados[] = $this->buildTh($this->getColumnName(4), 'ds_paciente', 'ds_paciente');
        return $encabezados;
    }

}
?>
