<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011 
 */
class OrdenpracticaTableModel extends ListarTableModel {

    private $columnNames = array();
    private $columnWidths = array();

    public function OrdenpracticaTableModel(ItemCollection $items) {
        $this->items = $items;
        $this->initColumns();
    }

    private function initColumns() {

        $this->columnNames[] = RYT_ORDENPRACTICA_CD_ORDENPRACTICA;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_ORDENPRACTICA_DT_CARGA;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_ORDENPRACTICA_CD_PACIENTE;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_ORDENPRACTICA_CD_PROFESIONAL;
        $this->columnWidths[] = 80;
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
     */
    function getTitle() {
        return "Ordenpracticas";
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
     */
    function getColumnCount() {
        return count($this->columnNames);
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
     */
    function getColumnName($columnIndex) {
        return $this->columnNames[$columnIndex];
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
     */
    function getColumnWidth($columnIndex) {
        return $this->columnWidths[$columnIndex];
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
     */
    function getRowCount() {
        $this->items->size();
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
     */
    function getValueAt($rowIndex, $columnIndex) {
        $oObject = $this->items->getObjectByIndex($rowIndex);
        return $this->getValue($oObject, $columnIndex);
    }

    public function getValue($anObject, $columnIndex) {
        $oOrdenpractica = $anObject;
        $value = 0;
        switch ($columnIndex) {

            case 0: $value = $oOrdenpractica->getCd_ordenpractica();
                break;

            case 1: $value = FuncionesComunes::fechaHoraMysqlaPHP($oOrdenpractica->getDt_carga());
                break;

            case 2: $value = $oOrdenpractica->getPaciente()->getDs_apynom();
                break;

            case 3: $value = $oOrdenpractica->getProfesional()->getDs_nombre();
                break;

            default: $value = '';
                break;
        }
        return $value;
    }

    public function getEncabezados() {

        $encabezados[] = $this->buildTh($this->getColumnName(0), 'cd_ordenpractica', 'cd_ordenpractica');

        $encabezados[] = $this->buildTh($this->getColumnName(1), 'dt_carga', 'dt_carga');

        $encabezados[] = $this->buildTh($this->getColumnName(2), 'cd_paciente', 'cd_paciente');

        $encabezados[] = $this->buildTh($this->getColumnName(3), 'ds_nombre', 'ds_nombre');

        return $encabezados;
    }

}
?>
