<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 12-12-2011 
 */ 
class PacienteobrasocialTableModel extends ListarTableModel{

	private $columnNames = array();

	private $columnWidths = array();
	
	public function PacienteobrasocialTableModel(ItemCollection $items){
		$this->items = $items;
		$this->initColumns();
	}
	
	private function initColumns(){
		
		$this->columnNames[] = RYT_PACIENTEOBRASOCIAL_CD_PACIENTEOBRASOCIAL;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = RYT_PACIENTEOBRASOCIAL_CD_PACIENTE;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = RYT_PACIENTEOBRASOCIAL_CD_OBRASOCIAL;
		$this->columnWidths[] = 80;
		
	}
	
		
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
	 */
	function getTitle(){
		return "Pacientesobrasociales";
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
	 */
	function getColumnCount(){
		return count($this->columnNames);
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
	 */
	function getColumnName($columnIndex){
		return $this->columnNames[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
	 */
	function getColumnWidth($columnIndex){
		return $this->columnWidths[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
	 */
	function getRowCount(){
		$this->items->size();
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
	 */
	function getValueAt($rowIndex, $columnIndex){
		$oObject = $this->items->getObjectByIndex($rowIndex);
		return $this->getValue($oObject, $columnIndex);
	}

	public function getValue($anObject, $columnIndex){
		$oPacienteobrasocial = $anObject;
		$value=0;
		switch ($columnIndex) {
			
			case 0: $value= $oPacienteobrasocial->getCd_pacienteobrasocial(); break;
			
			case 1: $value= $oPacienteobrasocial->getCd_paciente(); break;
			
			case 2: $value= $oPacienteobrasocial->getCd_obrasocial(); break;
			
			default: $value='';	break;
		}
		return $value;
	}
	
	public function getEncabezados(){
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(0), 'cd_pacienteobrasocial', 'cd_pacienteobrasocial');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(1), 'cd_paciente', 'cd_paciente');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(2), 'cd_obrasocial', 'cd_obrasocial');
	 	
	 	return $encabezados;	
	}
	
}
?>
