<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 24-11-2011 
 */
class PracticaobrasocialTableModel extends ListarTableModel {

    private $columnNames = array();
    private $columnWidths = array();

    public function PracticaobrasocialTableModel(ItemCollection $items) {
        $this->items = $items;
        $this->initColumns();
    }

    private function initColumns() {

        $this->columnNames[] = RYT_PRACTICAOBRASOCIAL_CD_PRACTICA;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_PRACTICAOBRASOCIAL_CD_OBRASOCIAL;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_PRACTICAOBRASOCIAL_NU_PRACTICAOS;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_PRACTICAOBRASOCIAL_NU_IMPORTE;
        $this->columnWidths[] = 80;

        $this->columnNames[] = RYT_PRACTICAOBRASOCIAL_DT_VIGENCIA;
        $this->columnWidths[] = 80;
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
     */
    function getTitle() {
        return "Practicaobrasociales";
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
     */
    function getColumnCount() {
        return count($this->columnNames);
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
     */
    function getColumnName($columnIndex) {
        return $this->columnNames[$columnIndex];
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
     */
    function getColumnWidth($columnIndex) {
        return $this->columnWidths[$columnIndex];
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
     */
    function getRowCount() {
        $this->items->size();
    }

    /**
     * (non-PHPdoc)
     * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
     */
    function getValueAt($rowIndex, $columnIndex) {
        $oObject = $this->items->getObjectByIndex($rowIndex);
        return $this->getValue($oObject, $columnIndex);
    }

    public function getValue($anObject, $columnIndex) {
        $oPracticaobrasocial = $anObject;
        $value = 0;
        switch ($columnIndex) {
            case 0: $value = $oPracticaobrasocial->getPractica()->getDs_practica();
                break;
            case 1: $value = $oPracticaobrasocial->getObrasocial()->getDs_obrasocial();
                break;
            case 2: $value = $oPracticaobrasocial->getNu_practicaos();
                break;
            case 3: $value = $oPracticaobrasocial->getNu_importe();
                break;
            case 4: $value = FuncionesComunes:: fechaMysqlaPHP($oPracticaobrasocial->getDt_vigencia());
                break;
            default: $value = '';
                break;
        }
        return $value;
    }

    public function getEncabezados() {
        $encabezados[] = $this->buildTh($this->getColumnName(0), 'P.ds_practica', 'Pr&aacute;ctica');
        $encabezados[] = $this->buildTh($this->getColumnName(1), 'O.ds_obrasocial', 'Obra social');
        $encabezados[] = $this->buildTh($this->getColumnName(2), 'nu_practicaos', 'Nomenclador');
        $encabezados[] = $this->buildTh($this->getColumnName(3), 'nu_importe', 'Importe');
        $encabezados[] = $this->buildTh($this->getColumnName(4), 'dt_vigencia', 'Vigencia');
        return $encabezados;
    }

}
?>
