<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 28-10-2011 
 */ 
class ProfesionalTableModel extends ListarTableModel{

	private $columnNames = array();

	private $columnWidths = array();
	
	public function ProfesionalTableModel(ItemCollection $items){
		$this->items = $items;
		$this->initColumns();
	}
	
	private function initColumns(){
		
		$this->columnNames[] = RYT_PROFESIONAL_CD_PROFESIONAL;
		$this->columnWidths[] = 80;
			
		$this->columnNames[] = RYT_PROFESIONAL_DS_NOMBRE;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = RYT_PROFESIONAL_NU_MATRICULA;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = RYT_PROFESIONAL_DS_TELEFONO;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = RYT_PROFESIONAL_DS_EMAIL;
		$this->columnWidths[] = 80;
		
	}
	
		
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
	 */
	function getTitle(){
		return "Profesionales";
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
	 */
	function getColumnCount(){
		return count($this->columnNames);
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
	 */
	function getColumnName($columnIndex){
		return $this->columnNames[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
	 */
	function getColumnWidth($columnIndex){
		return $this->columnWidths[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
	 */
	function getRowCount(){
		$this->items->size();
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
	 */
	function getValueAt($rowIndex, $columnIndex){
		$oObject = $this->items->getObjectByIndex($rowIndex);
		return $this->getValue($oObject, $columnIndex);
	}

	public function getValue($anObject, $columnIndex){
		$oProfesional = $anObject;
		$value=0;
		switch ($columnIndex) {
			
			case 0: $value= $oProfesional->getCd_profesional(); break;
			
			case 1: $value= $oProfesional->getDs_nombre(); break;
			
			case 2: $value= $oProfesional->getNu_matricula(); break;
			
			case 3: $value= $oProfesional->getDs_telefono(); break;
			
			case 4: $value= $oProfesional->getDs_email(); break;
			
			default: $value='';	break;
		}
		return $value;
	}
	
	public function getEncabezados(){
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(0), 'cd_profesional', 'cd_profesional');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(1), 'ds_nombre', 'ds_nombre');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(2), 'nu_matricula', 'nu_matricula');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(3), 'ds_telefono', 'ds_telefono');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(4), 'ds_email', 'ds_email');
	 	
	 	return $encabezados;	
	}
	
}
?>
