<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 05-12-2011 
 */ 
class TipoconceptoTableModel extends ListarTableModel{

	private $columnNames = array();

	private $columnWidths = array();
	
	public function TipoconceptoTableModel(ItemCollection $items){
		$this->items = $items;
		$this->initColumns();
	}
	
	private function initColumns(){
		
		$this->columnNames[] = RYT_TIPOCONCEPTO_CD_TIPOCONCEPTO;
		$this->columnWidths[] = 80;
		
		$this->columnNames[] = RYT_TIPOCONCEPTO_DS_TIPOCONCEPTO;
		$this->columnWidths[] = 80;
		
	}
	
		
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getTitle()
	 */
	function getTitle(){
		return "Tipoconceptos";
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnCount()
	 */
	function getColumnCount(){
		return count($this->columnNames);
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnName($columnIndex)
	 */
	function getColumnName($columnIndex){
		return $this->columnNames[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getColumnWidth($columnIndex)
	 */
	function getColumnWidth($columnIndex){
		return $this->columnWidths[$columnIndex];
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getRowCount()
	 */
	function getRowCount(){
		$this->items->size();
	}
	
	/**
	 * (non-PHPdoc)
	 * @see clases/com/cdt/view/tableModel/TableModel#getValueAt($rowIndex, $columnIndex)
	 */
	function getValueAt($rowIndex, $columnIndex){
		$oObject = $this->items->getObjectByIndex($rowIndex);
		return $this->getValue($oObject, $columnIndex);
	}

	public function getValue($anObject, $columnIndex){
		$oTipoconcepto = $anObject;
		$value=0;
		switch ($columnIndex) {
			
			case 0: $value= $oTipoconcepto->getCd_tipoconcepto(); break;
			
			case 1: $value= $oTipoconcepto->getDs_tipoconcepto(); break;
			
			default: $value='';	break;
		}
		return $value;
	}
	
	public function getEncabezados(){
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(0), 'cd_tipoconcepto', 'cd_tipoconcepto');
	 	
	 	$encabezados[]= $this->buildTh($this->getColumnName(1), 'ds_tipoconcepto', 'ds_tipoconcepto');
	 	
	 	return $encabezados;	
	}
	
}
?>
