<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 
 */
class BasicLayoutRYT extends LayoutDesktop {

    

    protected function getXTemplate($menuGroupActivo='', $menuOptions) {

       
            return new XTemplate(RYT_LAYOUT_TEMPLATE_BASIC);
    }

}

