<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 
 */
class LayoutRYTPanel extends LayoutRYT implements SecureLayout {

    public function setMenu($_menu) {

    }

    public function showLayout() {
        return $this->show();
    }

}