<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 22-12-2011
 */ 
class Anulacion { 
	
	//variables de instancia.
	
	private $cd_anulacion;
	
	private $oMovcaja;
	
	private $oMovcajaconcepto;
	
	private $dt_anulacion;
	
	private $nu_caja;
	
	private $oUsuario;
	
	private $oTurno;
	

	//Constructor.
	public function Anulacion() { 
		//TODO inicializar variables.
		
		
		$this->cd_anulacion = '';
		
		$this->dt_anulacion = '';
		
		$this->nu_caja = '';
		
		
		$this->oMovcaja = new Movcaja();
		
		$this->oMovcajaconcepto = new Movcajaconcepto();
		
		$this->oUsuario = new Usuario();
		
		$this->oTurno = new Turno();
		
	}

	//Getters	
		
	public function getCd_anulacion() { 
		return $this->cd_anulacion;
	}
		
	public function getMovcaja() { 
		return $this->oMovcaja;
	}
		
	public function getMovcajaconcepto() { 
		return $this->oMovcajaconcepto;
	}
		
	public function getDt_anulacion() { 
		return $this->dt_anulacion;
	}
		
	public function getNu_caja() { 
		return $this->nu_caja;
	}
		
	public function getUsuario() { 
		return $this->oUsuario;
	}
		
	public function getTurno() { 
		return $this->oTurno;
	}
	
		
	public function getCd_movcaja() { 
		return $this->oMovcaja->getCd_movcaja();
	}
		
	public function getCd_movcajaconcepto() { 
		return $this->oMovcajaconcepto->getCd_movcajaconcepto();
	}
		
	public function getCd_usuario() { 
		return $this->oUsuario->getCd_usuario();
	}
		
	public function getCd_turno() { 
		return $this->oTurno->getCd_turno();
	}
	

	//Setters
	
	public function setCd_anulacion( $value ) { 
		$this->cd_anulacion = $value;
	}
	
	public function setMovcaja( $value ) { 
		$this->oMovcaja = $value;
	}
	
	public function setMovcajaconcepto( $value ) { 
		$this->oMovcajaconcepto = $value;
	}
	
	public function setDt_anulacion( $value ) { 
		$this->dt_anulacion = $value;
	}
	
	public function setNu_caja( $value ) { 
		$this->nu_caja = $value;
	}
	
	public function setUsuario( $value ) { 
		$this->oUsuario = $value;
	}
	
	public function setTurno( $value ) { 
		$this->oTurno = $value;
	}
	
	
	public function setCd_movcaja( $value ) { 
		$this->oMovcaja->setCd_movcaja( $value );
	}
	
	public function setCd_movcajaconcepto( $value ) { 
		$this->oMovcajaconcepto->setCd_movcajaconcepto( $value );
	}
	
	public function setCd_usuario( $value ) { 
		$this->oUsuario->setCd_usuario( $value );
	}
	
	public function setCd_turno( $value ) { 
		$this->oTurno->setCd_turno( $value );
	}
	
} 
?>
