<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 05-12-2011
 */ 
class Concepto { 
	
	//variables de instancia.
	
	private $cd_concepto;
	
	private $oTipoconcepto;
	
	private $oTipooperacion;
	
	private $ds_concepto;
	

	//Constructor.
	public function Concepto() { 
		//TODO inicializar variables.
		
		
		$this->cd_concepto = '';
		
		$this->ds_concepto = '';
		
		
		$this->oTipoconcepto = new Tipoconcepto();
		
		$this->oTipooperacion = new Tipooperacion();
		
	}

	//Getters	
		
	public function getCd_concepto() { 
		return $this->cd_concepto;
	}
		
	public function getTipoconcepto() { 
		return $this->oTipoconcepto;
	}
		
	public function getTipooperacion() { 
		return $this->oTipooperacion;
	}
		
	public function getDs_concepto() { 
		return $this->ds_concepto;
	}
	
		
	public function getCd_tipoconcepto() { 
		return $this->oTipoconcepto->getCd_tipoconcepto();
	}
		
	public function getCd_tipooperacion() { 
		return $this->oTipooperacion->getCd_tipooperacion();
	}
	

	//Setters
	
	public function setCd_concepto( $value ) { 
		$this->cd_concepto = $value;
	}
	
	public function setTipoconcepto( $value ) { 
		$this->oTipoconcepto = $value;
	}
	
	public function setTipooperacion( $value ) { 
		$this->oTipooperacion = $value;
	}
	
	public function setDs_concepto( $value ) { 
		$this->ds_concepto = $value;
	}
	
	
	public function setCd_tipoconcepto( $value ) { 
		$this->oTipoconcepto->setCd_tipoconcepto( $value );
	}
	
	public function setCd_tipooperacion( $value ) { 
		$this->oTipooperacion->setCd_tipooperacion( $value );
	}
	
} 
?>
