<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 28-10-2011
 */ 
class Empleado { 
	
	//variables de instancia.
	
	private $cd_empleado;
	
	private $oTipoDocumento;
	
	private $nu_documento;
	
	private $ds_nombre;
	
	private $oTipoPersonal;
	
	private $ds_domicilio;
	
	private $ds_telefono;
	
	private $ds_email;
	

	//Constructor.
	public function Empleado() { 
		//TODO inicializar variables.
		
		
		$this->cd_empleado = '';
		
		$this->nu_documento = '';
		
		$this->ds_nombre = '';
		
		$this->ds_domicilio = '';
		
		$this->ds_telefono = '';
		
		$this->ds_email = '';
		
		
		$this->oTipoDocumento = new TipoDocumento();
		
		$this->oTipoPersonal = new TipoPersonal();
		
	}

	//Getters	
		
	public function getCd_empleado() { 
		return $this->cd_empleado;
	}
		
	public function getTipoDocumento() { 
		return $this->oTipoDocumento;
	}
		
	public function getNu_documento() { 
		return $this->nu_documento;
	}
		
	public function getDs_nombre() { 
		return $this->ds_nombre;
	}
		
	public function getTipoPersonal() { 
		return $this->oTipoPersonal;
	}
		
	public function getDs_domicilio() { 
		return $this->ds_domicilio;
	}
		
	public function getDs_telefono() { 
		return $this->ds_telefono;
	}
		
	public function getDs_email() { 
		return $this->ds_email;
	}
	
		
	public function getCd_tipodocumento() { 
		return $this->oTipoDocumento->getCd_tipodocumento();
	}
		
	public function getCd_tipopersonal() { 
		return $this->oTipoPersonal->getCd_tipopersonal();
	}
	

	//Setters
	
	public function setCd_empleado( $value ) { 
		$this->cd_empleado = $value;
	}
	
	public function setTipoDocumento( $value ) { 
		$this->oTipoDocumento = $value;
	}
	
	public function setNu_documento( $value ) { 
		$this->nu_documento = $value;
	}
	
	public function setDs_nombre( $value ) { 
		$this->ds_nombre = $value;
	}
	
	public function setTipoPersonal( $value ) { 
		$this->oTipoPersonal = $value;
	}
	
	public function setDs_domicilio( $value ) { 
		$this->ds_domicilio = $value;
	}
	
	public function setDs_telefono( $value ) { 
		$this->ds_telefono = $value;
	}
	
	public function setDs_email( $value ) { 
		$this->ds_email = $value;
	}
	
	
	public function setCd_tipodocumento( $value ) { 
		$this->oTipoDocumento->setCd_tipodocumento( $value );
	}
	
	public function setCd_tipopersonal( $value ) { 
		$this->oTipoPersonal->setCd_tipopersonal( $value );
	}
	
} 
?>
