<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011
 */ 
class Estadocaja { 
	
	//variables de instancia.
	
	private $cd_estadocaja;
	
	private $ds_estadocaja;
	

	//Constructor.
	public function Estadocaja() { 
		//TODO inicializar variables.
		
		
		$this->cd_estadocaja = '';
		
		$this->ds_estadocaja = '';
		
		
	}

	//Getters	
		
	public function getCd_estadocaja() { 
		return $this->cd_estadocaja;
	}
		
	public function getDs_estadocaja() { 
		return $this->ds_estadocaja;
	}
	
	

	//Setters
	
	public function setCd_estadocaja( $value ) { 
		$this->cd_estadocaja = $value;
	}
	
	public function setDs_estadocaja( $value ) { 
		$this->ds_estadocaja = $value;
	}
	
	
} 
?>
