<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011
 */ 
class Informe { 
	
	//variables de instancia.
	
	private $cd_informe;
	
	private $ds_apynom;
	
	private $ds_profesional;
	
	private $ds_estudiorx;
	
	private $ds_informe;
	

	//Constructor.
	public function Informe() { 
		//TODO inicializar variables.
		
		
		$this->cd_informe = '';
		
		$this->ds_apynom = '';
		
		$this->ds_profesional = '';
		
		$this->ds_estudiorx = '';
		
		$this->ds_informe = '';
		
		
	}

	//Getters	
		
	public function getCd_informe() { 
		return $this->cd_informe;
	}
		
	public function getDs_apynom() { 
		return $this->ds_apynom;
	}
		
	public function getDs_profesional() { 
		return $this->ds_profesional;
	}
		
	public function getDs_estudiorx() { 
		return $this->ds_estudiorx;
	}
		
	public function getDs_informe() { 
		return $this->ds_informe;
	}
	
	

	//Setters
	
	public function setCd_informe( $value ) { 
		$this->cd_informe = $value;
	}
	
	public function setDs_apynom( $value ) { 
		$this->ds_apynom = $value;
	}
	
	public function setDs_profesional( $value ) { 
		$this->ds_profesional = $value;
	}
	
	public function setDs_estudiorx( $value ) { 
		$this->ds_estudiorx = $value;
	}
	
	public function setDs_informe( $value ) { 
		$this->ds_informe = $value;
	}
	
	
} 
?>
