<?php

/**
 * Autogenerated class
 *
 *  @author modelBuilder
 *  @since 18-05-2021
 */
class Medio {

	//variables de instancia.

	private $cd_medio;

	private $ds_medio;


	//Constructor.
	public function Medio() {
		//TODO inicializar variables.


		$this->cd_medio = '';

		$this->ds_medio = '';


	}

	//Getters

	public function getCd_medio() {
		return $this->cd_medio;
	}

	public function getDs_medio() {
		return $this->ds_medio;
	}



	//Setters

	public function setCd_medio( $value ) {
		$this->cd_medio = $value;
	}

	public function setDs_medio( $value ) {
		$this->ds_medio = $value;
	}


}
?>
