<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011
 */
class Movcajaconcepto {

    //variables de instancia.

    private $cd_movcajaconcepto;
    private $oMovcaja;
    private $oConcepto;
    private $nu_importe;
    private $bl_tarjeta;
    private $cd_ordenpractica; //por si es un reintegro o una cancelación de deuda para saber a que orden está asociada
   	private $oPracticaordenpractica;
   //	private $oPracticaobrasocial;

    //Constructor.
    public function Movcajaconcepto() {
        //TODO inicializar variables.
        $this->cd_movcajaconcepto = '';
        $this->oMovcaja = new Movcaja();
        $this->oConcepto = new Concepto();
        /*$this->oPracticaordenpractica = new Practicaordenpractica();
        $this->oPracticaobrasocial = new Practicaobrasocial();*/
        $this->nu_importe = '';
        $this->bl_tarjeta = 0;
        $this->cd_ordenpractica = 0;
   
    }

    //Getters

    public function getCd_movcajaconcepto() {
        return $this->cd_movcajaconcepto;
    }

    public function getMovcaja() {
        return $this->oMovcaja;
    }

    public function getCd_movcaja() {
        return $this->getMovcaja()->getCd_movcaja();
    }

    public function getCd_concepto() {
        return $this->getConcepto()->getCd_concepto();
        ;
    }

    public function getConcepto() {
        return $this->oConcepto;
    }

    public function getPracticaordenpractica() {
        return $this->oPracticaordenpractica;
    }
    
	/*public function getPracticaobrasocial() {
        return $this->oPracticaobrasocial;
    }*/

    public function getNu_importe() {
        return $this->nu_importe;
    }

    //Setters

    public function setCd_movcajaconcepto($value) {
        $this->cd_movcajaconcepto = $value;
    }

    public function setMovcaja($value) {
        $this->oMovcaja = $value;
    }

    public function setCd_movcaja($value) {
        $this->getMovcaja()->setCd_movcaja($value);
    }

    public function setCd_concepto($value) {
        $this->getConcepto()->setCd_concepto($value);
    }

    public function setConcepto($oConcepto) {
        $this->oConcepto = $oConcepto;
    }

    public function setPracticaordenpractica($oPracticaordenpractica) {
        $this->oPracticaordenpractica = $oPracticaordenpractica;
    }

    public function setNu_importe($value) {
        $this->nu_importe = $value;
    }
    
	/*public function setPracticaobrasocial($oPracticaobrasocial) {
        $this->oPracticaobrasocial = $oPracticaobrasocial;
    }*/


    public function getCd_ordenpractica()
    {
        return $this->cd_ordenpractica;
    }

    public function setCd_ordenpractica($cd_ordenpractica)
    {
        $this->cd_ordenpractica = $cd_ordenpractica;
    }

    public function getBl_tarjeta()
    {
        return $this->bl_tarjeta;
    }

    public function setBl_tarjeta($bl_tarjeta)
    {
        $this->bl_tarjeta = $bl_tarjeta;
    }
}
?>
