<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011
 */
class Movcajacontrolpractica {

    //variables de instancia.

    private $cd_movcajacontrolpractica;
    
    private $Obrasocial;
    
    private $Practica1;
   
   private $Practica2;

    //Constructor.
    public function Movcajacontrolpractica() {
        //TODO inicializar variables.
        $this->cd_movcajacontrolpractica = '';
        $this->Obrasocial = new Obrasocial();
        $this->Practica1 = new Practica();
        $this->Practica2 = new Practica();
        
   
    }



   

    public function getCd_movcajacontrolpractica()
    {
        return $this->cd_movcajacontrolpractica;
    }

    public function setCd_movcajacontrolpractica($cd_movcajacontrolpractica)
    {
        $this->cd_movcajacontrolpractica = $cd_movcajacontrolpractica;
    }

    public function getObrasocial()
    {
        return $this->Obrasocial;
    }

    public function setObrasocial($Obrasocial)
    {
        $this->Obrasocial = $Obrasocial;
    }

    public function getPractica1()
    {
        return $this->Practica1;
    }

    public function setPractica1($Practica1)
    {
        $this->Practica1 = $Practica1;
    }

    public function getPractica2()
    {
        return $this->Practica2;
    }

    public function setPractica2($Practica2)
    {
        $this->Practica2 = $Practica2;
    }
}
?>
