<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 24-11-2011
 */ 
class Obrasocial { 
	
	//variables de instancia.
	
	private $cd_obrasocial;
	
	private $ds_obrasocial;
	
	private $bl_activa;
	

	//Constructor.
	public function Obrasocial() { 
		//TODO inicializar variables.
		
		
		$this->cd_obrasocial = '';
		
		$this->ds_obrasocial = '';
		
		$this->bl_activa = 1;
		
		
	}

	//Getters	
		
	public function getCd_obrasocial() { 
		return $this->cd_obrasocial;
	}
		
	public function getDs_obrasocial() { 
		return $this->ds_obrasocial;
	}
	
	

	//Setters
	
	public function setCd_obrasocial( $value ) { 
		$this->cd_obrasocial = $value;
	}
	
	public function setDs_obrasocial( $value ) { 
		$this->ds_obrasocial = $value;
	}
	
	

	public function getBl_activa()
	{
	    return $this->bl_activa;
	}

	public function setBl_activa($bl_activa)
	{
	    $this->bl_activa = $bl_activa;
	}
} 
?>
