<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011
 */
class Ordenpractica {

    //variables de instancia.

    private $cd_ordenpractica;
    private $dt_carga;
    private $cd_turno;
    private $oPaciente;
    private $oProfesional;
    private $cd_empleado;
    private $oObrasocial;
    private $bl_bono;
    private $nu_importebono;
    private $nu_reciboreintegro;
    private $oMovcaja;

    //Constructor.
    public function Ordenpractica() {
        //TODO inicializar variables.
        $this->cd_ordenpractica = '';
        $this->dt_carga = '';
        $this->cd_turno = '';
        $this->oPaciente = new Paciente();
        $this->oProfesional = new Profesional();
        $this->cd_empleado = '';
        $this->oObrasocial = new Obrasocial();
        $this->bl_bono = '';
        $this->nu_importebono = '';
        $this->oMovcaja = new Movcaja();
        $this->nu_reciboreintegro = '';
    }

    //Getters

    public function getCd_ordenpractica() {
        return $this->cd_ordenpractica;
    }

    public function getDt_carga() {
        return $this->dt_carga;
    }

    public function getCd_turno() {
        return $this->cd_turno;
    }

    public function getPaciente() {
        return $this->oPaciente;
    }

    public function getCd_paciente() {
        return $this->getPaciente()->getCd_paciente();
    }

    public function getCd_profesional() {
        return $this->getProfesional()->getCd_profesional();
    }

    public function getProfesional() {
        return $this->oProfesional;
    }

    public function getCd_empleado() {
        return $this->cd_empleado;
    }

    public function getObrasocial() {
        return $this->oObrasocial;
    }

    public function getCd_obrasocial() {
        return $this->getObrasocial()->getCd_obrasocial();
    }

    public function getMovcaja() {
        return $this->oMovcaja;
    }

    public function getCd_movcaja() {
        return $this->getMovcaja()->getCd_movcaja();
    }

    public function getBl_bono() {
        return $this->bl_bono;
    }

    public function getNu_importebono() {
        return $this->nu_importebono;
    }

    public function getNu_reciboreintegro() {
        return $this->nu_reciboreintegro;
    }

    //Setters

    public function setCd_ordenpractica($value) {
        $this->cd_ordenpractica = $value;
    }

    public function setDt_carga($value) {
        $this->dt_carga = $value;
    }

    public function setCd_turno($value) {
        $this->cd_turno = $value;
    }

    public function setCd_movcaja($value) {
        $this->getMovcaja()->setCd_movcaja($value);
    }

    public function setMovcaja($value) {
        $this->oMovcaja = $value;
    }

    public function setCd_paciente($value) {
        $this->getPaciente()->setCd_paciente($value);
    }

    public function setPaciente($value) {
        $this->oPaciente = $value;
    }

    public function setProfesional($value) {
        $this->oProfesional = $value;
    }

    public function setCd_profesional($value) {
        $this->getProfesional()->setCd_profesional($value);
    }

    public function setCd_empleado($value) {
        $this->cd_empleado = $value;
    }

    public function setObrasocial($value) {
        return $this->oObrasocial = $value;
    }

    public function setCd_obrasocial($value) {
        return $this->getObrasocial()->setCd_obrasocial($value);
    }

    public function setBl_bono($value) {
        $this->bl_bono = $value;
    }

    public function setNu_importebono($value) {
        $this->nu_importebono = $value;
    }

    public function setNu_reciboreintegro($value) {
        $this->nu_reciboreintegro = $value;
    }

}
?>
