<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 12-12-2011
 */ 
class Paciente { 
	
	//variables de instancia.
	
	private $cd_paciente;
	
	private $ds_apynom;
	
	private $oTipodoc;
	
	private $nu_doc;
	
	private $ds_direccion;
	
	private $ds_telefono;
	
	private $ds_email;
	
	private $dt_nacimiento;
	

	//Constructor.
	public function Paciente() { 
		//TODO inicializar variables.
		
		
		$this->cd_paciente = '';
		
		$this->ds_apynom = '';
		
		$this->oTipodoc = new TipoDocumento();
		
		$this->nu_doc = '';
		
		$this->ds_direccion = '';
		
		$this->ds_telefono = '';
		
		$this->ds_email = '';
		
		$this->dt_nacimiento = '';
		
		
	}

	//Getters	
		
	public function getCd_paciente() { 
		return $this->cd_paciente;
	}
		
	public function getDs_apynom() { 
		return $this->ds_apynom;
	}
	
        public function getTipodoc() { 
		return $this->oTipodoc;
	}

	public function getCd_tipodoc() { 
		return $this->getTipodoc()->getCd_tipodocumento();
	}
		
	public function getNu_doc() { 
		return $this->nu_doc;
	}
		
	public function getDs_direccion() { 
		return $this->ds_direccion;
	}
		
	public function getDs_telefono() { 
		return $this->ds_telefono;
	}
		
	public function getDs_email() { 
		return $this->ds_email;
	}
	
	

	//Setters
	
	public function setCd_paciente( $value ) { 
		$this->cd_paciente = $value;
	}
	
	public function setDs_apynom( $value ) { 
		$this->ds_apynom = $value;
	}

        public function setTipodoc( $value ) {
		$this->oTipodoc = $value;
	}

	public function setCd_tipodoc( $value ) { 
		$this->getTipodoc()->setCd_tipodocumento($value);
	}
	
	public function setNu_doc( $value ) { 
		$this->nu_doc = $value;
	}
	
	public function setDs_direccion( $value ) { 
		$this->ds_direccion = $value;
	}
	
	public function setDs_telefono( $value ) { 
		$this->ds_telefono = $value;
	}
	
	public function setDs_email( $value ) { 
		$this->ds_email = $value;
	}
	
	

	public function getDt_nacimiento()
	{
	    return $this->dt_nacimiento;
	}

	public function setDt_nacimiento($dt_nacimiento)
	{
	    $this->dt_nacimiento = $dt_nacimiento;
	}
} 
?>
