<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 24-11-2011
 */ 
class Practica { 
	
	//variables de instancia.
	
	private $cd_practica;
	
	private $ds_practica;
	
	private $bl_activa;
	

	//Constructor.
	public function Practica() { 
		//TODO inicializar variables.
		
		
		$this->cd_practica = '';
		
		$this->ds_practica = '';
		
		$this->bl_activa = '';
		
		
	}

	//Getters	
		
	public function getCd_practica() { 
		return $this->cd_practica;
	}
		
	public function getDs_practica() { 
		return $this->ds_practica;
	}
	
	

	//Setters
	
	public function setCd_practica( $value ) { 
		$this->cd_practica = $value;
	}
	
	public function setDs_practica( $value ) { 
		$this->ds_practica = $value;
	}
	
	

	public function getBl_activa()
	{
	    return $this->bl_activa;
	}

	public function setBl_activa($bl_activa)
	{
	    $this->bl_activa = $bl_activa;
	}
} 
?>
