<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011
 */
class Practicaordenpractica {

    //variables de instancia.

    private $cd_practicaordenpractica;
    private $oPracticaobrasocial;
    private $oOrdenpractica;
    private $nu_cantplacas;
    private $nu_cantdigital;
    private $nu_cantnodigital;
    private $nu_repeticiones;
    private $oInforme;
    private $oMovcajaconcepto;
    private $oLiquidacionprofesional;
    private $cd_aporteos;
    private $ds_pieza;

    //Constructor.
    public function Practicaordenpractica() {
        //TODO inicializar variables.
        $this->cd_practicaordenpractica = '';
        $this->oPracticaobrasocial = new Practicaobrasocial();
        $this->oOrdenpractica = new Ordenpractica();
        $this->nu_cantplacas = '';
        $this->nu_cantdigital = '';
        $this->nu_cantnodigital = '';
        $this->nu_repeticiones = '';
        $this->oInforme = new Informe();
        $this->oMovcajaconcepto = new Movcajaconcepto();
        $this->nu_importealiquidar = '';
        $this->oLiquidacionprofesional = new Liquidacionprofesional();
        $this->cd_aporteos = '';
        $this->ds_pieza = '';
    }

    //Getters

    public function getCd_practicaordenpractica() {
        return $this->cd_practicaordenpractica;
    }

    public function getPracticaobrasocial() {
        return $this->oPracticaobrasocial;
    }

     public function getDs_practica() {
        return $this->getPracticaobrasocial()->getPractica()->getDs_practica();
    }

    public function getCd_practicaobrasocial() {
        return $this->getPracticaobrasocial()->getCd_obrasocial();
    }

    public function getOrdenpractica() {
        return $this->oOrdenpractica;
    }

    public function getCd_ordenpractica() {
        return $this->getOrdenpractica()->getCd_ordenpractica();
    }

    public function getNu_cantplacas() {
        return $this->nu_cantplacas;
    }

    public function getNu_cantdigital() {
        return $this->nu_cantdigital;
    }

    public function getNu_cantnodigital() {
        return $this->nu_cantnodigital;
    }

    public function getNu_importealiquidar() {
        return '$'.(float) round($this->nu_importealiquidar, 2);
    }

    public function getNu_repeticiones() {
        return $this->nu_repeticiones;
    }

    public function getInforme() {
        return $this->oInforme;
    }

    public function getCd_informe() {
        return $this->getInforme()->getCd_informe();
    }

    public function getMovcajaconcepto() {
        return $this->oMovcajaconcepto;
    }

    public function getCd_movcajaconcepto() {
        return $this->getMovcajaconcepto()->getCd_movcajaconcepto();
    }

    public function getCd_movcaja() {
        return $this->getMovcajaconcepto()->getMovcaja()->getCd_movcaja();
    }

    public function getDt_movcaja() {
        return $this->getMovcajaconcepto()->getMovcaja()->getDt_movcaja();
    }
    
    

    public function getLiquidacionprofesional() {
        return $this->oLiquidacionprofesional;
    }

    public function getCd_liquidacionprofesional() {
        return $this->getLiquidacionprofesional()->getCd_liquidacionprofesional();
    }

    public function getCd_aporteos() {
        return $this->cd_aporteos;
    }

    //Setters

    public function setCd_practicaordenpractica($value) {
        $this->cd_practicaordenpractica = $value;
    }

    public function setPracticaobrasocial($value) {
        $this->oPracticaobrasocial = $value;
    }

    public function setCd_practicaobrasocial($value) {
        $this->getPracticaobrasocial()->setCd_obrasocial($value);
    }

    public function setOrdenpractica($value) {
        return $this->oOrdenpractica = $value;
    }

    public function setCd_ordenpractica($value) {
        return $this->getOrdenpractica()->setCd_ordenpractica($value);
    }

    public function setNu_cantplacas($value) {
        $this->nu_cantplacas = $value;
    }

    public function setNu_cantdigital($value) {
        $this->nu_cantdigital = $value;
    }

    public function setNu_cantnodigital($value) {
        $this->nu_cantnodigital = $value;
    }

    public function setNu_importealiquidar($value) {
        $this->nu_importealiquidar = $value;
    }

    public function setNu_repeticiones($value) {
        $this->nu_repeticiones = $value;
    }

    public function setInforme($value) {
        $this->oInforme = $value;
    }

    public function setCd_informe($value) {
        $this->getInforme()->setCd_informe($value);
    }

    public function setMovcajaconcepto($value) {
        $this->oMovcajaconcepto = $value;
    }

    public function setCd_movcajaconcepto($value) {
        $this->getMovcajaconcepto()->setCd_movcajaconcepto($value);
    }

    public function setLiquidacionprofesional($value) {
        $this->oLiquidacionprofesional = $value;
    }

    public function setCd_liquidacionprofesional($value) {
        $this->getLiquidacionprofesional()->setCd_liquidacionprofesional($value);
    }

    public function setCd_aporteos($value) {
        $this->cd_aporteos = $value;
    }


    public function getDs_pieza()
    {
        return $this->ds_pieza;
    }

    public function setDs_pieza($ds_pieza)
    {
        $this->ds_pieza = $ds_pieza;
    }
}
?>
