<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011
 */ 
class Procesocaja { 
	
	//variables de instancia.
	
	private $cd_procesocaja;
	
	private $nu_caja;
	
	private $cd_turno;
	
	private $cd_usuario;
	
	private $cd_movcaja;
	
	private $cd_estadocaja;
	
	private $dt_procesocaja;
	
	private $nu_importe;
	

	//Constructor.
	public function Procesocaja() { 
		//TODO inicializar variables.
		
		
		$this->cd_procesocaja = '';
		
		$this->nu_caja = '';
		
		$this->cd_turno = '';
		
		$this->cd_usuario = '';
		
		$this->cd_movcaja = '';
		
		$this->cd_estadocaja = '';
		
		$this->dt_procesocaja = '';
		
		$this->nu_importe = '';
		
		
	}

	//Getters	
		
	public function getCd_procesocaja() { 
		return $this->cd_procesocaja;
	}
		
	public function getNu_caja() { 
		return $this->nu_caja;
	}
		
	public function getCd_turno() { 
		return $this->cd_turno;
	}
		
	public function getCd_usuario() { 
		return $this->cd_usuario;
	}
		
	public function getCd_movcaja() { 
		return $this->cd_movcaja;
	}
		
	public function getCd_estadocaja() { 
		return $this->cd_estadocaja;
	}
		
	public function getDt_procesocaja() { 
		return $this->dt_procesocaja;
	}
		
	public function getNu_importe() { 
		return $this->nu_importe;
	}
	
	

	//Setters
	
	public function setCd_procesocaja( $value ) { 
		$this->cd_procesocaja = $value;
	}
	
	public function setNu_caja( $value ) { 
		$this->nu_caja = $value;
	}
	
	public function setCd_turno( $value ) { 
		$this->cd_turno = $value;
	}
	
	public function setCd_usuario( $value ) { 
		$this->cd_usuario = $value;
	}
	
	public function setCd_movcaja( $value ) { 
		$this->cd_movcaja = $value;
	}
	
	public function setCd_estadocaja( $value ) { 
		$this->cd_estadocaja = $value;
	}
	
	public function setDt_procesocaja( $value ) { 
		$this->dt_procesocaja = $value;
	}
	
	public function setNu_importe( $value ) { 
		$this->nu_importe = $value;
	}
	
	
} 
?>
