<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 28-10-2011
 */ 
class Profesional { 
	
	//variables de instancia.
	
	private $cd_profesional;
	
	private $oTipoDocumento;
	
	private $nu_documento;
	
	private $ds_nombre;
	
	private $nu_matricula;
	
	private $ds_domicilio;
	
	private $ds_telefono;
	
	private $ds_email;
	

	//Constructor.
	public function Profesional() { 
		//TODO inicializar variables.
		
		
		$this->cd_profesional = '';
		
		$this->nu_documento = '';
		
		$this->ds_nombre = '';
		
		$this->nu_matricula = '';
		
		$this->ds_domicilio = '';
		
		$this->ds_telefono = '';
		
		$this->ds_email = '';
		
		
		$this->oTipoDocumento = new TipoDocumento();
		
	}

	//Getters	
		
	public function getCd_profesional() { 
		return $this->cd_profesional;
	}
		
	public function getTipoDocumento() { 
		return $this->oTipoDocumento;
	}
		
	public function getNu_documento() { 
		return $this->nu_documento;
	}
		
	public function getDs_nombre() { 
		return $this->ds_nombre;
	}
		
	public function getNu_matricula() { 
		return $this->nu_matricula;
	}
		
	public function getDs_domicilio() { 
		return $this->ds_domicilio;
	}
		
	public function getDs_telefono() { 
		return $this->ds_telefono;
	}
		
	public function getDs_email() { 
		return $this->ds_email;
	}
	
		
	public function getCd_tipodocumento() { 
		return $this->oTipoDocumento->getCd_tipodocumento();
	}
	

	//Setters
	
	public function setCd_profesional( $value ) { 
		$this->cd_profesional = $value;
	}
	
	public function setTipoDocumento( $value ) { 
		$this->oTipoDocumento = $value;
	}
	
	public function setNu_documento( $value ) { 
		$this->nu_documento = $value;
	}
	
	public function setDs_nombre( $value ) { 
		$this->ds_nombre = $value;
	}
	
	public function setNu_matricula( $value ) { 
		$this->nu_matricula = $value;
	}
	
	public function setDs_domicilio( $value ) { 
		$this->ds_domicilio = $value;
	}
	
	public function setDs_telefono( $value ) { 
		$this->ds_telefono = $value;
	}
	
	public function setDs_email( $value ) { 
		$this->ds_email = $value;
	}
	
	
	public function setCd_tipodocumento( $value ) { 
		$this->oTipoDocumento->setCd_tipodocumento( $value );
	}
	
} 
?>
