<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 28-10-2011
 */ 
class TipoPersonal { 
	
	//variables de instancia.
	
	private $cd_tipopersonal;
	
	private $ds_tipopersonal;
	

	//Constructor.
	public function TipoPersonal() { 
		//TODO inicializar variables.
		
		
		$this->cd_tipopersonal = '';
		
		$this->ds_tipopersonal = '';
		
		
	}

	//Getters	
		
	public function getCd_tipopersonal() { 
		return $this->cd_tipopersonal;
	}
		
	public function getDs_tipopersonal() { 
		return $this->ds_tipopersonal;
	}
	
	

	//Setters
	
	public function setCd_tipopersonal( $value ) { 
		$this->cd_tipopersonal = $value;
	}
	
	public function setDs_tipopersonal( $value ) { 
		$this->ds_tipopersonal = $value;
	}
	
	
} 
?>
