<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 05-12-2011
 */ 
class Tipooperacion { 
	
	//variables de instancia.
	
	private $cd_tipooperacion;
	
	private $ds_tipooperacion;
	

	//Constructor.
	public function Tipooperacion() { 
		//TODO inicializar variables.
		
		
		$this->cd_tipooperacion = '';
		
		$this->ds_tipooperacion = '';
		
		
	}

	//Getters	
		
	public function getCd_tipooperacion() { 
		return $this->cd_tipooperacion;
	}
		
	public function getDs_tipooperacion() { 
		return $this->ds_tipooperacion;
	}
	
	

	//Setters
	
	public function setCd_tipooperacion( $value ) { 
		$this->cd_tipooperacion = $value;
	}
	
	public function setDs_tipooperacion( $value ) { 
		$this->ds_tipooperacion = $value;
	}
	
	
} 
?>
