<?php

/**
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 05-12-2011
 */
class Tipoconcepto {

    //variables de instancia.

    private $cd_tipoconcepto;
    private $ds_tipoconcepto;
    private $bl_oculto;

    //Constructor.
    public function Tipoconcepto() {
        //TODO inicializar variables.


        $this->cd_tipoconcepto = '';

        $this->ds_tipoconcepto = '';
        $this->bl_oculto = 0;
    }

    //Getters

    public function getCd_tipoconcepto() {
        return $this->cd_tipoconcepto;
    }

    public function getDs_tipoconcepto() {
        return $this->ds_tipoconcepto;
    }

    public function getBl_oculto(){
        return $this->bl_oculto;
    }

    //Setters

    public function setCd_tipoconcepto($value) {
        $this->cd_tipoconcepto = $value;
    }

    public function setDs_tipoconcepto($value) {
        $this->ds_tipoconcepto = $value;
    }

    public function setBl_oculto($value) {
        $this->bl_oculto = $value;
    }

}
?>
