<?php 

/** 
 * Autogenerated class 
 *  
 *  @author modelBuilder 
 *  @since 14-12-2011
 */ 
class Turno { 
	
	//variables de instancia.
	
	private $cd_turno;
	
	private $ds_turno;
	

	//Constructor.
	public function Turno() { 
		//TODO inicializar variables.
		
		
		$this->cd_turno = '';
		
		$this->ds_turno = '';
		
		
	}

	//Getters	
		
	public function getCd_turno() { 
		return $this->cd_turno;
	}
		
	public function getDs_turno() { 
		return $this->ds_turno;
	}
	
	

	//Setters
	
	public function setCd_turno( $value ) { 
		$this->cd_turno = $value;
	}
	
	public function setDs_turno( $value ) { 
		$this->ds_turno = $value;
	}
	
	
} 
?>
